/* VprGrid 风格介绍库·电子与地下半：俱乐部支流、地下重型与网络微流派。
   与 genres-world.js 合并去重后供新标签页的风格卡片抽取。 */

export const GENRES_NET = [
  {
    id: "gqom",
    en: "Gqom",
    zh: "格库姆",
    whereZh: "南非 · 德班 · 2010s",
    whereEn: "Durban, South Africa · 2010s",
    zhDesc: "把 house 的四四拍掰成瘸腿的三连音，低音在地下室里闷响，人声只剩一句咒语般的反复，专为德班小巴的车载音响调过音。",
    enDesc: "House bent into a limping triplet stomp: subs booming like a basement, one chanted vocal loop, tuned for Durban taxi sound systems.",
    key: "Rudeboyz — Rudeboyz EP",
  },
  {
    id: "bacardi-house",
    en: "Bacardi House",
    zh: "巴卡迪浩室",
    whereZh: "南非 · 比勒陀利亚 · 2000s",
    whereEn: "Pretoria, South Africa · 2000s",
    zhDesc: "比勒陀利亚黑人城镇的自制 house：廉价键盘敲出跳跃的三音动机，鼓点抢在拍前落地，短促、干燥，配合当地那套抬腿舞步。",
    enDesc: "Township house from Pretoria: cheap-keyboard three-note hooks, drums landing ahead of the beat, dry and short, built around a local high-step dance.",
    key: "DJ Mujava — \"Township Funk\"",
  },
  {
    id: "singeli",
    en: "Singeli",
    zh: "辛盖利",
    whereZh: "坦桑尼亚 · 达累斯萨拉姆 · 2010s",
    whereEn: "Dar es Salaam, Tanzania · 2010s",
    zhDesc: "达累斯萨拉姆贫民区的极速舞曲，鼓机能跑到每分钟三百拍，采样自 taarab 与老 hip-hop 的碎片被抽成尖锐的短促循环，MC 在上面连珠炮式喊话。",
    enDesc: "Slum-born speed dance from Dar es Salaam past 300 BPM: shards of taarab and old hip-hop cut into shrill loops, MCs rattling on top.",
    key: "Sisso — Singeli Ya Maajabu",
  },
  {
    id: "electro-chaabi",
    en: "Electro Chaabi / Mahraganat",
    zh: "电子沙比（马赫拉加纳特）",
    whereZh: "埃及 · 开罗 · 2010s",
    whereEn: "Cairo, Egypt · 2010s",
    zhDesc: "开罗街区婚礼的音乐进了廉价录音棚：键盘模仿的爆响打击、失真到破音的人声、把 auto-tune 当乐器用，歌词直接骂物价与警察。",
    enDesc: "Cairo street-wedding music through a cheap studio: blown-out keyboard percussion, vocals distorted past clipping, auto-tune as an instrument, lyrics about rent and cops.",
    key: "Islam Chipsy & EEK — Kahraba",
  },
  {
    id: "kuduro",
    en: "Kuduro",
    zh: "库都罗",
    whereZh: "安哥拉 · 罗安达 · 1990s–2000s",
    whereEn: "Luanda, Angola · 1990s–2000s",
    zhDesc: "罗安达的硬派电子舞曲：semba 的切分节奏塞进廉价软件，鼓组硬得像敲铁皮，喊麦短句循环推进，跳的人靠肩膀和膝盖发力。",
    enDesc: "Hard electronic dance from Luanda: semba syncopation rebuilt in cheap software, tin-hard drums, shouted refrains, danced from the shoulders and knees.",
    key: "Buraka Som Sistema — Black Diamond",
  },
  {
    id: "funk-bruxaria",
    en: "Funk Bruxaria",
    zh: "巫术放克",
    whereZh: "巴西 · 圣保罗 · 2020s",
    whereEn: "São Paulo, Brazil · 2020s",
    zhDesc: "圣保罗贫民区 funk 的极端分支：低音被推成一团失真的黑影，节奏碎成不规则的跺脚，人声采样倒放、拉长，故意做出邪门恐怖片的气味。",
    enDesc: "The extreme edge of São Paulo favela funk: bass shoved into distorted black smoke, rhythms broken into irregular stomps, vocals reversed for horror-film menace.",
    key: "DJ K — Panico No Submundo",
  },
  {
    id: "funk-proibidao",
    en: "Proibidão",
    zh: "禁曲放克",
    whereZh: "巴西 · 里约 · 1990s–2000s",
    whereEn: "Rio de Janeiro, Brazil · 1990s–2000s",
    zhDesc: "里约山城派对上不进电台的那一批 funk：只有一台鼓机的 tamborzão 节奏、街头帮派的实况唱词，录音糙得像现场翻录的磁带。",
    enDesc: "The Rio hillside funk radio wouldn't touch: bare tamborzão drum-machine pattern, gang reportage as lyrics, sound quality of a party tape dubbed twice.",
    key: "V/A — Rio Baile Funk: Favela Booty Beats",
  },
  {
    id: "dembow-dominicano",
    en: "Dominican Dembow",
    zh: "多米尼加登波",
    whereZh: "多米尼加 · 圣多明各 · 2000s–10s",
    whereEn: "Santo Domingo, Dominican Republic · 2000s–10s",
    zhDesc: "把牙买加 riddim 那一记「哒-哒-哒」抽出来无限循环，配上尖细的电子口哨与喊话式说唱，节奏快、句子短、几乎不留呼吸的空隙。",
    enDesc: "One Jamaican riddim kick pattern looped forever, topped with shrill synth whistles and shouted raps — fast, clipped, barely a gap to breathe.",
    key: "El Alfa — \"Suave\"",
  },
  {
    id: "kwaito",
    en: "Kwaito",
    zh: "夸伊托",
    whereZh: "南非 · 索韦托 · 1990s",
    whereEn: "Soweto, South Africa · 1990s",
    zhDesc: "把 house 的速度拖慢到走路的节奏，贝斯线肥厚，人声用祖鲁语与街头俚语半唱半说——种族隔离结束那几年南非城镇的派对声。",
    enDesc: "House slowed to walking pace with fat bass lines and half-sung Zulu street slang — the sound of township parties in the years apartheid ended.",
    key: "Boom Shaka — \"It's About Time\"",
  },
  {
    id: "private-school-amapiano",
    en: "Private School Amapiano",
    zh: "私校阿玛皮阿诺",
    whereZh: "南非 · 约翰内斯堡 · 2010s–20s",
    whereEn: "Johannesburg, South Africa · 2010s–20s",
    zhDesc: "amapiano 里安静讲究的那一支：log drum 的滑音留足空隙，爵士味的电钢与人声碎片飘着，速度不快，冷静得像凌晨四点的车厢。",
    enDesc: "The quiet, fastidious branch of amapiano: sliding log drums with air around them, jazzy electric piano, vocal shards, calm as a 4 a.m. car ride.",
    key: "Kabza De Small & DJ Maphorisa — Scorpion Kings",
  },
  {
    id: "baltimore-club",
    en: "Baltimore Club",
    zh: "巴尔的摩俱乐部",
    whereZh: "美国 · 巴尔的摩 · 1990s",
    whereEn: "Baltimore, USA · 1990s",
    zhDesc: "八拍一个循环的破碎鼓组，永远躲不开那两句采样（Lyn Collins 的尖叫与 Gaz 的鼓点），人声只用来喊口令，专门服务舞池上的斗舞。",
    enDesc: "Broken eight-bar loops built on two inescapable samples, vocals reduced to shouted commands — engineered for dance battles on a crowded floor.",
    key: "Rod Lee — Vol. 5: The Official",
  },
  {
    id: "juke-footwork",
    en: "Footwork",
    zh: "芝加哥快步",
    whereZh: "美国 · 芝加哥 · 2000s",
    whereEn: "Chicago, USA · 2000s",
    zhDesc: "160 拍上下的机械三连音，低音闷成一记记拳，同一句人声被剁成十几段抽风般重复——为舞者脚下的对拼而写，不为坐着听。",
    enDesc: "Machine triplets around 160 BPM, bass landing like body blows, one vocal chopped into a dozen stuttering pieces — written for dancers' feet, not for sitting.",
    key: "DJ Rashad — Double Cup",
  },
  {
    id: "ghettotech",
    en: "Ghettotech",
    zh: "底特律贫民科技",
    whereZh: "美国 · 底特律 · 1990s",
    whereEn: "Detroit, USA · 1990s",
    zhDesc: "底特律把 techno、electro 和 Miami bass 拌进一台鼓机，速度推到 150 拍以上，混音只留骨架，DJ 靠急促的切歌把整晚拉着往前跑。",
    enDesc: "Detroit stirring techno, electro and Miami bass into one drum machine past 150 BPM, mixes stripped to bone, DJs cutting tracks every ninety seconds.",
    key: "DJ Assault — Belle Isle Tech",
  },
  {
    id: "ghetto-house",
    en: "Ghetto House",
    zh: "贫民浩室",
    whereZh: "美国 · 芝加哥 · 1990s",
    whereEn: "Chicago, USA · 1990s",
    zhDesc: "芝加哥 Dance Mania 一系的极简 house：909 的底鼓、一根循环贝斯、一句反复的口号，粗糙、便宜、直奔跳舞这一件事。",
    enDesc: "Minimal house from Chicago's Dance Mania stable: a 909 kick, one looping bass, one repeated chant — cheap, coarse, aimed squarely at dancing.",
    key: "V/A — Hardcore Traxx: Dance Mania Records 1986–1997",
  },
  {
    id: "new-orleans-bounce",
    en: "New Orleans Bounce",
    zh: "新奥尔良弹跳",
    whereZh: "美国 · 新奥尔良 · 1990s",
    whereEn: "New Orleans, USA · 1990s",
    zhDesc: "两段固定采样（Triggerman 与 Brown Beat）撑起整个流派，MC 用点名的方式喊街区与人名，节奏永远保持在能连续摇臀的那个速度。",
    enDesc: "A whole genre built on two fixed samples, with MCs calling out wards and names over a beat locked at the tempo you can keep shaking to.",
    key: "DJ Jubilee — \"Do the Jubilee All\"",
  },
  {
    id: "miami-booty-bass",
    en: "Miami Booty Bass",
    zh: "迈阿密臀低音",
    whereZh: "美国 · 迈阿密 · 1980s–90s",
    whereEn: "Miami, USA · 1980s–90s",
    zhDesc: "808 的低音被推到音箱纸盆发抖，速度快、鼓点脆，主角不是旋律而是那条能把后备箱震开的次低频。",
    enDesc: "808 bass pushed until the cone flaps, fast and crisp on top; the hook isn't a melody but the sub that rattles a car trunk open.",
    key: "Dynamix II — \"Just Give the DJ a Break\"",
  },
  {
    id: "uk-funky",
    en: "UK Funky",
    zh: "英式放克浩室",
    whereZh: "英国 · 伦敦 · 2000s 末",
    whereEn: "London, UK · late 2000s",
    zhDesc: "伦敦把 soca 与非洲手鼓的碎拍搭在 house 的骨架上，低音克制，主唱唱情歌，节奏却一直在侧面挠人。",
    enDesc: "London laying soca and West African hand-drum patterns over a house frame: restrained bass, a love-song vocal, rhythm nudging sideways throughout.",
    key: "Crazy Cousinz — \"Do You Mind\"",
  },
  {
    id: "bassline-niche",
    en: "Bassline (Niche)",
    zh: "谢菲尔德低音房",
    whereZh: "英国 · 谢菲尔德 · 2000s",
    whereEn: "Sheffield, UK · 2000s",
    zhDesc: "从 speed garage 长出来的北方分支：一根弹簧似的方波贝斯扛起全曲，R&B 女声在上面唱，四四拍稳到可以踩着走。",
    enDesc: "The northern offshoot of speed garage: one springy square-wave bass carrying everything, an R&B vocal above, four-four steady enough to march to.",
    key: "T2 — \"Heartbroken\"",
  },
  {
    id: "speed-garage",
    en: "Speed Garage",
    zh: "极速车库",
    whereZh: "英国 · 伦敦 · 1990s",
    whereEn: "London, UK · 1990s",
    zhDesc: "把纽约 house 提速，塞进 jungle 那种翻滚的低音与雷鬼式的 MC 喊场，军鼓打在意料之外的地方，是英国车库乐最躁的那一版。",
    enDesc: "New York house sped up and fitted with jungle's rolling bass and ragga MC hype, snares landing off-expectation — UK garage at its rowdiest.",
    key: "Double 99 — \"RIP Groove\"",
  },
  {
    id: "eskibeat",
    en: "Eskibeat",
    zh: "爱斯基节拍",
    whereZh: "英国 · 东伦敦 · 2000s 初",
    whereEn: "East London, UK · early 2000s",
    zhDesc: "grime 最初的骨架：廉价软件里冷冰冰的方波与钟琴音色，八拍一循环，空得只剩节奏与寒气，为 MC 的连珠炮腾出全部空间。",
    enDesc: "Grime's original skeleton: icy square waves and bell tones from cheap software, eight-bar loops left almost empty so the MC can fill them.",
    key: "Wiley — \"Eskimo\"",
  },
  {
    id: "weightless-grime",
    en: "Weightless Grime",
    zh: "失重格赖姆",
    whereZh: "英国 · 伦敦 · 2010s",
    whereEn: "London, UK · 2010s",
    zhDesc: "把 grime 的低音整条抽掉，只留下金属敲击、气流与远处的合成器长音，节奏悬在半空，像在空旷停车场里听一场没有低频的舞会。",
    enDesc: "Grime with the bass removed entirely: metallic hits, air and distant synth pads, the rhythm suspended — a dance in an empty car park.",
    key: "Mumdance & Logos — Proto",
  },
  {
    id: "future-garage",
    en: "Future Garage",
    zh: "未来车库",
    whereZh: "英国 · 2000s 末",
    whereEn: "UK · late 2000s",
    zhDesc: "2-step 的碎拍泡在混响里，人声被拉高变调、剪成叹息，低频温和地压着，整体像隔着雨夜的窗户听一支旧派对。",
    enDesc: "2-step shuffle soaked in reverb, vocals pitched up and cut into sighs, bass pressing gently — an old rave heard through a rainy window.",
    key: "Burial — Untrue",
  },
  {
    id: "deconstructed-club",
    en: "Deconstructed Club",
    zh: "解构俱乐部",
    whereZh: "柏林与全球 · 2010s",
    whereEn: "Berlin & global · 2010s",
    zhDesc: "把舞曲拆成零件再故意装不回去：金属撞击、玻璃碎裂、突然的静默与失控的低音，好听与不适之间反复试探。",
    enDesc: "Dance music taken apart and deliberately misassembled: metal impacts, shattering glass, sudden silence and unstable bass, testing the line between pleasure and unease.",
    key: "Lotic — Power",
  },
  {
    id: "hard-drum",
    en: "Hard Drum",
    zh: "硬鼓",
    whereZh: "英国 · 布里斯托与伦敦 · 2010s",
    whereEn: "Bristol & London, UK · 2010s",
    zhDesc: "去掉旋律，只留手鼓、木块与金属击打排成的循环，130 拍上下，空间开阔而干燥，像把全球打击乐塞进极简 techno 的骨架。",
    enDesc: "Melody removed, leaving loops of hand drums, woodblocks and metal hits around 130 BPM — global percussion in a minimal techno frame.",
    key: "TSVI — Inner Worlds",
  },
  {
    id: "dub-techno",
    en: "Dub Techno",
    zh: "回响科技",
    whereZh: "德国 · 柏林 · 1990s",
    whereEn: "Berlin, Germany · 1990s",
    zhDesc: "一记和弦通过磁带回声无限衰减，底鼓像远处的心跳，全曲十分钟只发生一点点变化，听的是空气与噪底的厚度。",
    enDesc: "One chord decaying through tape echo forever, a kick like a distant heartbeat, ten minutes where almost nothing changes but the thickness of the air.",
    key: "Basic Channel — BCD",
  },
  {
    id: "microhouse",
    en: "Microhouse",
    zh: "微型浩室",
    whereZh: "德国 · 科隆 · 2000s",
    whereEn: "Cologne, Germany · 2000s",
    zhDesc: "用几百个几毫秒的碎片拼出摇摆：咳嗽声、开关声、唱片噪音都成了打击乐，house 的律动还在，材料却全换成生活噪音。",
    enDesc: "Groove assembled from hundreds of millisecond fragments — coughs, switches, vinyl noise as percussion — house swing built from household sound.",
    key: "Akufen — My Way",
  },
  {
    id: "industrial-techno",
    en: "Industrial Techno",
    zh: "工业科技",
    whereZh: "英国与柏林 · 2010s",
    whereEn: "UK & Berlin · 2010s",
    zhDesc: "把 techno 推进红区：底鼓过载失真、金属反馈当旋律用、混响像水泥厂房，四四拍在噪音里硬撑住秩序。",
    enDesc: "Techno pushed into the red: overloaded kicks, metal feedback used as melody, concrete-hall reverb, four-four holding order inside the noise.",
    key: "Perc — The Power and the Glory",
  },
  {
    id: "hardgroove-techno",
    en: "Hardgroove Techno",
    zh: "硬律动科技",
    whereZh: "英国 · 伦敦 · 1990s",
    whereEn: "London, UK · 1990s",
    zhDesc: "底特律的摇摆感配上更硬的鼓：手鼓与 hi-hat 层层叠加成不断打滚的律动，速度不快却停不下来，DJ 常三台盘一起推。",
    enDesc: "Detroit swing with harder drums: congas and hats stacked into a rolling groove that never lets up, usually mixed three decks at a time.",
    key: "Ben Sims — Manipulated",
  },
  {
    id: "schranz",
    en: "Schranz",
    zh: "施兰茨",
    whereZh: "德国 · 法兰克福 · 2000s",
    whereEn: "Frankfurt, Germany · 2000s",
    zhDesc: "德国硬派 techno：一段砂纸质地的循环 loop 从头刮到尾，底鼓密不透风，靠效果器扫频推动，属于凌晨四点的大棚。",
    enDesc: "German hard techno: one sandpaper loop scraping start to finish over an airtight kick, driven by filter sweeps — 4 a.m. warehouse fare.",
    key: "V/A — Schranz Total 1",
  },
  {
    id: "free-tekno",
    en: "Free Tekno / Tribe",
    zh: "自由锐舞铁克诺",
    whereZh: "英国与法国 · 1990s",
    whereEn: "UK & France · 1990s",
    zhDesc: "无照野派对的音乐：底鼓打满、酸线扭到尖叫、采样来自政治广播与老电影，为了发电机与卡车音响而写，不为俱乐部。",
    enDesc: "Music for unlicensed outdoor raves: relentless kicks, acid lines screwed to a scream, samples off political broadcasts — made for generators and truck rigs.",
    key: "Spiral Tribe — \"Forward the Revolution\"",
  },
  {
    id: "early-hardcore-gabber",
    en: "Early Hardcore (Gabber)",
    zh: "早期硬核（加伯）",
    whereZh: "荷兰 · 鹿特丹 · 1990s",
    whereEn: "Rotterdam, Netherlands · 1990s",
    zhDesc: "鹿特丹对阿姆斯特丹 house 的回击：底鼓压成一记记失真的闷响，速度冲到 190 拍，采样越粗野越好，配合原地跳跺的舞步。",
    enDesc: "Rotterdam's answer to Amsterdam house: kicks distorted into blunt thuds, tempos to 190 BPM, samples as crude as possible, danced on the spot.",
    key: "Rotterdam Termination Source — \"Poing\"",
  },
  {
    id: "frenchcore",
    en: "Frenchcore",
    zh: "法式硬核",
    whereZh: "法国 · 巴黎 · 1990s–2000s",
    whereEn: "Paris, France · 1990s–2000s",
    zhDesc: "从自由派对长出来的极速硬核：200 拍上下的滚动底鼓、断头式的采样切换，比荷兰派更神经质、更爱突然掉进静音。",
    enDesc: "Speed hardcore out of the free-party scene: rolling kicks near 200 BPM, guillotine sample edits, more neurotic than the Dutch strain and fond of sudden silence.",
    key: "Micropoint — Neurophonie",
  },
  {
    id: "uptempo-hardcore",
    en: "Uptempo Hardcore",
    zh: "极速硬核",
    whereZh: "荷兰与法国 · 2010s",
    whereEn: "Netherlands & France · 2010s",
    zhDesc: "把硬核推到 200 拍以上，底鼓被压缩成尖锐的一记「叮」，旋律部分反而写得像庆典号角，暴力与欢腾同时拉满。",
    enDesc: "Hardcore past 200 BPM with kicks compressed into a sharp ping, while the melodies turn festival-bright — violence and elation at once.",
    key: "Dr. Peacock — \"Trip to Pattaya\"",
  },
  {
    id: "happy-hardcore",
    en: "Happy Hardcore",
    zh: "欢乐硬核",
    whereZh: "英国 · 1990s",
    whereEn: "UK · 1990s",
    zhDesc: "170 拍的碎拍配上加速的女声与糖分过量的钢琴 riff，天真到近乎悲伤——英国锐舞退潮后留在青少年迪斯科里的那一支。",
    enDesc: "170 BPM breaks under sped-up female vocals and sugar-overloaded piano riffs, so naive it turns sad — what stayed in teen discos after the rave ebbed.",
    key: "Force & Styles — \"Heart of Gold\"",
  },
  {
    id: "darkside-jungle",
    en: "Darkside Jungle",
    zh: "暗面丛林",
    whereZh: "英国 · 伦敦 · 1993–95",
    whereEn: "London, UK · 1993–95",
    zhDesc: "锐舞的欢快被抽掉之后剩下的东西：加速的碎拍、恐怖片弦乐、低到发闷的贝斯，采样里全是警笛与不安的对白。",
    enDesc: "What was left when rave's euphoria drained out: accelerated breaks, horror-film strings, bass sunk to a muffle, samples of sirens and uneasy dialogue.",
    key: "Metalheadz — Platinum Breakz",
  },
  {
    id: "techstep",
    en: "Techstep",
    zh: "科技步",
    whereZh: "英国 · 1990s 末",
    whereEn: "UK · late 1990s",
    zhDesc: "把 drum & bass 的暖意换成金属：贝斯像液压机的呼吸，鼓组干硬、无摇摆，整体是科幻片工厂内部的声音。",
    enDesc: "Drum & bass with the warmth swapped for metal: bass breathing like hydraulics, drums dry and swingless — the inside of a sci-fi factory.",
    key: "Ed Rush & Optical — Wormhole",
  },
  {
    id: "neurofunk",
    en: "Neurofunk",
    zh: "神经放克",
    whereZh: "荷兰与英国 · 2000s",
    whereEn: "Netherlands & UK · 2000s",
    zhDesc: "techstep 之后的精密化版本：贝斯被调制成不断变形的机械嗓音，每一小节都在换音色，制作精度高到像在听工程演示。",
    enDesc: "The precision-engineered descendant of techstep: bass modulated into a shifting mechanical voice, timbre changing every bar, produced like an engineering demo.",
    key: "Noisia — Split the Atom",
  },
  {
    id: "ragga-jungle",
    en: "Ragga Jungle",
    zh: "雷鬼丛林",
    whereZh: "英国 · 伦敦 · 1990s",
    whereEn: "London, UK · 1990s",
    zhDesc: "把牙买加 dancehall 的唱段贴到加速碎拍上，低音走 dub 的路线，鼓组翻滚得像散架的机器，是英国黑人锐舞最直接的一支。",
    enDesc: "Jamaican dancehall vocals pasted onto accelerated breaks with dub bass underneath, drums rolling like a machine coming apart.",
    key: "Congo Natty — Jungle Revolution",
  },
  {
    id: "breakcore",
    en: "Breakcore",
    zh: "碎拍核",
    whereZh: "加拿大与欧洲 · 2000s",
    whereEn: "Canada & Europe · 2000s",
    zhDesc: "把 amen break 剁到分子级别再重排，密度高到接近噪音，中间却常插进古典弦乐或民谣采样，暴力与伤感贴在一起。",
    enDesc: "The amen break diced to molecules and rebuilt at near-noise density, then cut with classical strings or folk samples — violence pressed against grief.",
    key: "Venetian Snares — Rossz Csillag Alatt Született",
  },
  {
    id: "forest-psytrance",
    en: "Forest Psytrance",
    zh: "森林迷幻电子",
    whereZh: "俄罗斯与芬兰 · 2000s",
    whereEn: "Russia & Finland · 2000s",
    zhDesc: "为林间派对写的迷幻电子：低音线像虫群移动，音色潮湿、有机，声场里满是拟真的鸟叫与滴水，气氛偏诡异而非狂欢。",
    enDesc: "Psychedelic trance for woodland parties: bass lines moving like insect swarms, damp organic timbres, birdcalls and dripping water — eerie rather than euphoric.",
    key: "Kindzadza — Nano Nucleonica",
  },
  {
    id: "darkpsy",
    en: "Darkpsy",
    zh: "暗黑迷幻",
    whereZh: "德国与俄罗斯 · 1990s 末起",
    whereEn: "Germany & Russia · late 1990s on",
    zhDesc: "速度推到 160 拍以上的迷幻电子，采样取自恐怖片与生化实验，音色刺耳、结构扭曲，听感更接近噩梦而不是舞池。",
    enDesc: "Psytrance past 160 BPM with horror-film and lab-experiment samples, harsh timbres and warped structures — closer to a nightmare than a dancefloor.",
    key: "Xenomorph — Cassandra's Nightmare",
  },
  {
    id: "rominimal",
    en: "Rominimal",
    zh: "罗式极简",
    whereZh: "罗马尼亚 · 布加勒斯特 · 2010s",
    whereEn: "Bucharest, Romania · 2010s",
    zhDesc: "布加勒斯特那派极简 house：低音只走几个音，细碎的打击乐在立体声里绕圈，一首曲子十几分钟只慢慢改变一点点。",
    enDesc: "Bucharest's minimal house: bass reduced to a few notes, tiny percussion circling in stereo, a track shifting only fractionally across fifteen minutes.",
    key: "Petre Inspirescu — Nowhere/Now Here",
  },
  {
    id: "detroit-electro",
    en: "Detroit Electro",
    zh: "底特律电子",
    whereZh: "美国 · 底特律 · 1990s",
    whereEn: "Detroit, USA · 1990s",
    zhDesc: "808 的机械切分配上水下感的和声与变声人声，主题常是逃亡、深海与未来神话，冷、快、带着叙事。",
    enDesc: "808 machine syncopation under submarine harmonies and vocoded voices, themed on escape, deep water and future myth — cold, fast, narrative.",
    key: "Drexciya — Neptune's Lair",
  },
  {
    id: "hague-electro",
    en: "The Hague Electro",
    zh: "海牙电子",
    whereZh: "荷兰 · 海牙 · 1990s",
    whereEn: "The Hague, Netherlands · 1990s",
    zhDesc: "把 electro 与 Italo disco 的廉价浪漫混在一起，模拟合成器调得刺耳发糙，态度反商业到近乎挑衅。",
    enDesc: "Electro crossed with the cheap romance of Italo disco, analogue synths tuned harsh and grainy, an anti-commercial stance bordering on provocation.",
    key: "I-F — Fucking Consumer",
  },
  {
    id: "florida-breaks",
    en: "Florida Breaks",
    zh: "佛州碎拍",
    whereZh: "美国 · 奥兰多 · 1990s",
    whereEn: "Orlando, USA · 1990s",
    zhDesc: "把 Miami bass 的低音接到碎拍上，节奏摇摆而不冲，中段留出长长的滤波推进，是九十年代美国 club 里最好跳的一支。",
    enDesc: "Miami bass low end welded to breakbeats: swinging rather than driving, long filtered build-ups — the most danceable strain in 1990s US clubs.",
    key: "DJ Icey — Generate",
  },
  {
    id: "clicks-and-cuts",
    en: "Clicks & Cuts",
    zh: "点击与切口",
    whereZh: "德国 · 法兰克福 · 1990s 末",
    whereEn: "Frankfurt, Germany · late 1990s",
    zhDesc: "故意把数字故障当素材：爆音、断点、CD 跳针被排成节奏，旋律近乎不存在，听的是错误本身的质感。",
    enDesc: "Digital failure used as material: clipping, dropouts and CD skips arranged into rhythm, melody nearly absent — the texture of error itself.",
    key: "V/A — Clicks_+_Cuts",
  },
  {
    id: "lowercase",
    en: "Lowercase",
    zh: "小写声音",
    whereZh: "美国 · 2000s",
    whereEn: "USA · 2000s",
    zhDesc: "把几乎听不见的声音放大成整张专辑：纸张摩擦、蜡烛燃烧、细微的电流嗡鸣，需要把音量拧大才开始出现内容。",
    enDesc: "Barely audible sound amplified into whole albums — paper friction, a burning candle, faint current hum — content that only appears once you turn it up.",
    key: "Steve Roden — Forms of Paper",
  },
  {
    id: "onkyo-eai",
    en: "Onkyo / EAI",
    zh: "音响派与电声即兴",
    whereZh: "日本 · 东京 · 1990s–2000s",
    whereEn: "Tokyo, Japan · 1990s–2000s",
    zhDesc: "用无输入调音台、反馈与静默即兴：声音稀薄、留白极长，两个演奏者常十几秒才各出一声，听的是房间与耳朵的关系。",
    enDesc: "Improvising with no-input mixers, feedback and silence: sparse events, enormous gaps, two players sounding once every ten seconds — a music about rooms and ears.",
    key: "Toshimaru Nakamura — No-Input Mixing Board",
  },
  {
    id: "harsh-noise-wall",
    en: "Harsh Noise Wall",
    zh: "噪音墙",
    whereZh: "法国与美国 · 2000s",
    whereEn: "France & USA · 2000s",
    zhDesc: "一整面不变的静态噪音从第一秒挂到最后一秒，没有动态、没有事件，纪律严格到近乎极简主义的一个恶作剧。",
    enDesc: "One unchanging slab of static from first second to last: no dynamics, no events — a discipline so strict it verges on minimalist prank.",
    key: "Vomir — Proanomie",
  },
  {
    id: "power-electronics",
    en: "Power Electronics",
    zh: "力量电子",
    whereZh: "英国 · 1980s",
    whereEn: "UK · 1980s",
    zhDesc: "没有节奏与旋律，只有失控的合成器高频与嘶喊，音量与压迫感就是全部结构，现场比录音更难承受。",
    enDesc: "No rhythm, no melody — runaway synth treble and screamed vocals, with volume and pressure as the only structure; live it is harder to take than on record.",
    key: "Whitehouse — Birthdeath Experience",
  },
  {
    id: "death-industrial",
    en: "Death Industrial",
    zh: "死亡工业",
    whereZh: "瑞典 · 1990s",
    whereEn: "Sweden · 1990s",
    zhDesc: "低频轰鸣、金属废料的回响与含混的呻吟层层堆叠，节奏几近停滞，像在废弃工厂的地下室里缓慢下沉。",
    enDesc: "Low-frequency rumble, scrap-metal reverb and muffled groans stacked into near-static slabs — sinking slowly in an abandoned factory basement.",
    key: "Brighter Death Now — Great Death",
  },
  {
    id: "japanoise",
    en: "Japanoise",
    zh: "日本噪音",
    whereZh: "日本 · 大阪与东京 · 1980s–90s",
    whereEn: "Osaka & Tokyo, Japan · 1980s–90s",
    zhDesc: "把效果器链推到彻底饱和，全频段同时爆发，没有段落也没有休止，几十年下来发展出各自可辨的「噪音笔迹」。",
    enDesc: "Effect chains driven to total saturation, all frequencies erupting at once with no sections or rests — decades in, each artist has a recognisable noise handwriting.",
    key: "Incapacitants — Repo",
  },
  {
    id: "hauntology",
    en: "Hauntology",
    zh: "幽灵学",
    whereZh: "英国 · 2000s",
    whereEn: "UK · 2000s",
    zhDesc: "用旧教育片配乐、公共电视片头与磁带噪音重造一个从未存在过的英国童年，音色发霉、剪辑跳接，怀旧得让人不安。",
    enDesc: "Old educational-film scores, public-TV idents and tape hiss rebuilt into a British childhood that never happened — mouldy timbres, jump-cut edits, nostalgia turned uneasy.",
    key: "The Focus Group — Hey Let Loose Your Love",
  },
  {
    id: "plunderphonics",
    en: "Plunderphonics",
    zh: "掠夺声音",
    whereZh: "加拿大 · 1980s",
    whereEn: "Canada · 1980s",
    zhDesc: "只用别人的录音当材料：把一首名曲逐帧拆开重排，原曲还认得出来，意义却被彻底改写，也因此吃过唱片公司的官司。",
    enDesc: "Built only from other people's recordings: a famous track dismantled frame by frame and reassembled — recognisable, meaning rewritten, and duly sued over.",
    key: "John Oswald — Plunderphonic",
  },
  {
    id: "chipmusic",
    en: "Chipmusic (LSDJ)",
    zh: "芯片音乐",
    whereZh: "欧美网络场景 · 2000s",
    whereEn: "Europe & US net scene · 2000s",
    zhDesc: "在 Game Boy 里用 LSDJ 写曲：四条音轨、方波与噪音通道，限制逼出旋律功力，现场就是一台掌机接进 PA。",
    enDesc: "Composed inside a Game Boy with LSDJ: four channels of square waves and noise, limits forcing melodic craft, performed with a handheld plugged into the PA.",
    key: "Sabrepulse — Empty Spaces",
  },
  {
    id: "demoscene-tracker",
    en: "Demoscene Tracker Music",
    zh: "演示场景追踪器乐",
    whereZh: "北欧 · 1990s",
    whereEn: "Nordic countries · 1990s",
    zhDesc: "为电脑演示程序写的音乐，用采样表与追踪器逐格排好，容量常被压到几十 KB，旋律因此写得极为紧凑抓耳。",
    enDesc: "Written for computer demos in trackers, cell by cell, often squeezed into a few dozen kilobytes — which is why the melodies are so tightly hooked.",
    key: "Purple Motion — \"Second Reality\"",
  },
  {
    id: "west-coast-modular",
    en: "West Coast Modular Synthesis",
    zh: "西岸模块合成",
    whereZh: "美国 · 加州 · 1970s 起",
    whereEn: "California, USA · 1970s on",
    zhDesc: "Buchla 一脉的思路：不按键盘、不追音准，用随机源与复杂振荡器让声音自己长出形状，结果常在旋律与鸟叫之间。",
    enDesc: "The Buchla lineage: no keyboard, no fixed pitch — random sources and complex oscillators letting sound grow its own shape, landing between melody and birdsong.",
    key: "Kaitlyn Aurelia Smith — Ears",
  },
  {
    id: "illbient",
    en: "Illbient",
    zh: "病态氛围",
    whereZh: "美国 · 布鲁克林 · 1990s",
    whereEn: "Brooklyn, USA · 1990s",
    zhDesc: "把 hip-hop 的采样手法用在氛围音乐上：迟缓的鼓、厚重的低音雾、城市噪音与短波电台混在一起，听着像纽约夏夜的地铁风口。",
    enDesc: "Hip-hop sampling applied to ambient: sluggish drums, thick bass fog, street noise and shortwave radio — a New York subway vent in summer.",
    key: "DJ Spooky — Songs of a Dead Dreamer",
  },
  {
    id: "dungeon-synth",
    en: "Dungeon Synth",
    zh: "地牢合成",
    whereZh: "挪威 · 1990s",
    whereEn: "Norway · 1990s",
    zhDesc: "用最廉价的键盘音色摹写中世纪与幻想地牢：单薄的弦乐预设、缓慢的进行曲、磁带噪音，业余感恰恰是它的魅力。",
    enDesc: "Medieval fantasy dungeons sketched on the cheapest keyboard presets: thin string patches, slow marches, tape hiss — the amateurism is the charm.",
    key: "Mortiis — Født til å Herske",
  },
  {
    id: "winter-synth",
    en: "Winter Synth",
    zh: "冬日合成",
    whereZh: "芬兰与美国 · 2010s",
    whereEn: "Finland & USA · 2010s",
    zhDesc: "dungeon synth 的雪原分支：长长的合成弦乐铺成白色平面，风声与铃声偶尔穿过，气温感比旋律更重要。",
    enDesc: "The snowfield branch of dungeon synth: long synth strings spread into white planes, wind and bells passing through — temperature matters more than melody.",
    key: "Old Sorcery — Realms of Magickal Sorrow",
  },
  {
    id: "ritual-dark-ambient",
    en: "Ritual Dark Ambient",
    zh: "仪式暗黑氛围",
    whereZh: "瑞典 · 1990s",
    whereEn: "Sweden · 1990s",
    zhDesc: "以低频轰鸣为地基，叠上远处的诵经、金属碰撞与洞穴混响，几乎没有节奏，像在一座空教堂里等着什么发生。",
    enDesc: "Low-frequency drone as foundation with distant chanting, struck metal and cave reverb, almost rhythmless — waiting for something in an empty church.",
    key: "raison d'être — Prospectus I",
  },
  {
    id: "isolationism",
    en: "Isolationism",
    zh: "孤立主义氛围",
    whereZh: "英国 · 1990s 中",
    whereEn: "UK · mid-1990s",
    zhDesc: "九十年代对「舒适氛围」的反面：冷、空、带工业锈味的长音，没有旋律安慰，只有距离感与低温。",
    enDesc: "The 1990s counter to comfortable ambient: cold, empty, rust-tinged drones with no melodic comfort — only distance and low temperature.",
    key: "V/A — Isolationism",
  },
  {
    id: "drone-doom",
    en: "Drone Doom",
    zh: "长音末日",
    whereZh: "美国 · 西雅图 · 1990s",
    whereEn: "Seattle, USA · 1990s",
    zhDesc: "把金属乐的失真拉成极慢的长音，一个和弦能撑几分钟，鼓几乎不出现，靠音量与泛音的堆叠制造压强。",
    enDesc: "Metal distortion stretched into extremely slow drones, one chord held for minutes, drums nearly absent — pressure built from volume and overtones.",
    key: "Earth — Earth 2",
  },
  {
    id: "funeral-doom",
    en: "Funeral Doom",
    zh: "葬礼末日",
    whereZh: "芬兰 · 1990s 初",
    whereEn: "Finland · early 1990s",
    zhDesc: "速度慢到接近停止，和弦像挽歌一样一记记落下，人声在深处低吼，一首曲子往往十几分钟只走完一段旋律。",
    enDesc: "Slowed almost to a halt, chords falling like a dirge, vocals growling from far below — fifteen minutes to complete one melodic line.",
    key: "Thergothon — Stream from the Heavens",
  },
  {
    id: "death-doom",
    en: "Death-Doom",
    zh: "死亡末日",
    whereZh: "澳大利亚与英国 · 1990s 初",
    whereEn: "Australia & UK · early 1990s",
    zhDesc: "死亡金属的重量配上末日金属的速度：段落在极慢与突然加速之间切换，气氛沉重、混音刻意浑浊。",
    enDesc: "Death metal's weight at doom's tempo, sections lurching between crawl and sudden acceleration, mixes deliberately murky.",
    key: "diSEMBOWELMENT — Transcendence into the Peripheral",
  },
  {
    id: "dissonant-black-metal",
    en: "Dissonant Black Metal",
    zh: "不谐黑金属",
    whereZh: "法国 · 2000s",
    whereEn: "France · 2000s",
    zhDesc: "把黑金属的和声全部拧歪：不解决的音程、爬行式的吉他线、突然的静默段落，结构像一篇故意写乱的神学论文。",
    enDesc: "Black metal with the harmony wrenched out of true: unresolving intervals, crawling guitar lines, abrupt silences — structured like a deliberately deranged theological text.",
    key: "Deathspell Omega — Fas – Ite, Maledicti, in Ignem Aeternum",
  },
  {
    id: "blackgaze",
    en: "Blackgaze",
    zh: "黑色瞪鞋",
    whereZh: "法国 · 2010s",
    whereEn: "France · 2010s",
    zhDesc: "把 shoegaze 的混响墙接到黑金属的连奏鼓上：嘶喊被埋在吉他的洪流下面，听感明亮又悲伤，像在雪地里跑。",
    enDesc: "Shoegaze reverb walls welded to black metal blast beats: screams buried under a guitar flood, bright and grieving at once — running through snow.",
    key: "Alcest — Écailles de Lune",
  },
  {
    id: "war-metal",
    en: "War Metal / Bestial Black",
    zh: "战争金属",
    whereZh: "加拿大 · 温哥华 · 1990s",
    whereEn: "Vancouver, Canada · 1990s",
    zhDesc: "刻意把录音做成一团轰鸣：鼓像雪崩、吉他辨不清和弦、人声在底下咆哮，追求的是失控而不是清晰。",
    enDesc: "Recording deliberately reduced to one avalanche: drums as landslide, chords indecipherable, vocals bellowing underneath — chaos preferred over clarity.",
    key: "Blasphemy — Fallen Angel of Doom",
  },
  {
    id: "atmospheric-sludge",
    en: "Atmospheric Sludge / Post-Metal",
    zh: "氛围泥浆金属",
    whereZh: "美国 · 旧金山湾区 · 1990s",
    whereEn: "San Francisco Bay Area, USA · 1990s",
    zhDesc: "把重型 riff 拉长成十分钟的地质运动，中间插入部落式打击与安静段落，音量与情绪一起缓慢积累到崩塌。",
    enDesc: "Heavy riffs stretched into ten-minute geological movements with tribal percussion and quiet passages, volume and feeling accumulating until collapse.",
    key: "Neurosis — Through Silver in Blood",
  },
  {
    id: "mathcore",
    en: "Mathcore",
    zh: "数学核",
    whereZh: "美国 · 新泽西 · 1990s 末",
    whereEn: "New Jersey, USA · late 1990s",
    zhDesc: "把 hardcore 的暴力拆进变态拍号：每两秒换一次节奏、吉他线像被扯断的电缆，演奏精度和噪音量同时拉到极限。",
    enDesc: "Hardcore violence broken across deranged time signatures: the meter shifting every two seconds, guitar lines like snapped cable, precision and noise maxed together.",
    key: "The Dillinger Escape Plan — Calculating Infinity",
  },
  {
    id: "powerviolence",
    en: "Powerviolence",
    zh: "力量暴力",
    whereZh: "美国 · 加州 · 1990s",
    whereEn: "California, USA · 1990s",
    zhDesc: "把 hardcore 压到三十秒一首：极快的段落突然掉进泥浆般的慢速，再突然结束，专辑一面能塞进二十首。",
    enDesc: "Hardcore compressed to thirty seconds a song: blistering bursts dropping into sludge tempo and cutting off — twenty tracks a side.",
    key: "Man Is the Bastard — Sum of the Whole",
  },
  {
    id: "mincecore",
    en: "Mincecore",
    zh: "绞肉核",
    whereZh: "比利时 · 1980s–90s",
    whereEn: "Belgium · 1980s–90s",
    zhDesc: "grindcore 里最朴素的一支：录音粗糙、riff 简单重复、歌词直白反战反资本，几十年如一日地自印磁带交换。",
    enDesc: "The plainest branch of grindcore: raw recordings, simple repeated riffs, blunt anti-war lyrics, and decades of self-dubbed tape trading.",
    key: "Agathocles — Theatric Symbolisation of Life",
  },
  {
    id: "cybergrind",
    en: "Cybergrind",
    zh: "电子绞核",
    whereZh: "美国 · 2000s",
    whereEn: "USA · 2000s",
    zhDesc: "把编程鼓机塞进 grindcore：鼓点快到不像人类，合成器与故障音效贴在失真吉他上，段落切换像换台。",
    enDesc: "Programmed drums inside grindcore: beats too fast to be human, synths and glitch effects pasted onto distorted guitar, sections switching like channels.",
    key: "Genghis Tron — Dead Mountain Mouth",
  },
  {
    id: "skramz",
    en: "Skramz / Emoviolence",
    zh: "尖叫情绪核",
    whereZh: "美国 · 新英格兰 · 1990s",
    whereEn: "New England, USA · 1990s",
    zhDesc: "情绪硬核里最失控的一支：嗓子喊到破音、编曲在混乱与突然的清亮之间反复摔，录音多是地下室现场质感。",
    enDesc: "The most unravelled strain of emotional hardcore: voices screamed past breaking, arrangements lurching between chaos and sudden clarity, recorded in basements.",
    key: "Orchid — Chaos Is Me",
  },
  {
    id: "egg-punk",
    en: "Egg Punk",
    zh: "蛋朋克",
    whereZh: "美国 · 中西部 · 2010s",
    whereEn: "US Midwest · 2010s",
    zhDesc: "把车库朋克的速度配上廉价合成器与变调怪腔，编曲神经兮兮、录音故意做薄，网络场景里自己起的绰号。",
    enDesc: "Garage punk speed with cheap synths and pitched-up yelping, arrangements twitchy and recordings deliberately thin — a nickname the net scene gave itself.",
    key: "Lumpy and the Dumpers — Huff My Sack",
  },
  {
    id: "kbd-punk",
    en: "KBD Punk",
    zh: "KBD 朋克",
    whereZh: "欧美各地 · 1970s 末–80s 初",
    whereEn: "Europe & USA · late 1970s–early 1980s",
    zhDesc: "由一套地下合辑定义的类别：小镇乐队自费压的单曲，两分钟、跑调、录音爆掉，反而成了朋克最生猛的一批文献。",
    enDesc: "A category defined by one bootleg compilation series: self-pressed small-town singles, two minutes, out of tune, blown-out — punk's rawest paperwork.",
    key: "V/A — Killed by Death #1",
  },
  {
    id: "d-beat",
    en: "D-Beat",
    zh: "D 拍",
    whereZh: "瑞典 · 1980s",
    whereEn: "Sweden · 1980s",
    zhDesc: "整支流派建立在一种鼓型上：Discharge 那记不断滚动的军鼓，吉他只用两三个和弦，歌词全是核战与末日。",
    enDesc: "A whole genre built on one drum pattern — Discharge's rolling snare — with two or three chords and lyrics of nuclear war and aftermath.",
    key: "Anti Cimex — Victims of a Bomb Raid",
  },
  {
    id: "anarcho-punk",
    en: "Anarcho-Punk",
    zh: "无政府朋克",
    whereZh: "英国 · 1980s",
    whereEn: "UK · 1980s",
    zhDesc: "把朋克当成政治工具：拼贴式的唱片封套、拒绝商业发行、歌词直指战争与体制，音乐粗砺而结构常常出人意料。",
    enDesc: "Punk as political tool: collaged sleeves, refusal of commercial release, lyrics aimed at war and the state, music raw but structurally unpredictable.",
    key: "Crass — The Feeding of the 5000",
  },
  {
    id: "riot-grrrl",
    en: "Riot Grrrl",
    zh: "暴女",
    whereZh: "美国 · 奥林匹亚 · 1990s 初",
    whereEn: "Olympia, USA · early 1990s",
    zhDesc: "西北部女性主导的朋克浪潮：三分钟一首、结构直白、嗓音在唱与喊之间切换，同人小志与演出现场同等重要。",
    enDesc: "A women-led punk wave from the Pacific Northwest: three-minute songs, plain structures, voices flipping between singing and shouting — zines as vital as gigs.",
    key: "Bikini Kill — Pussy Whipped",
  },
  {
    id: "queercore",
    en: "Queercore",
    zh: "酷儿核",
    whereZh: "北美 · 1990s",
    whereEn: "North America · 1990s",
    zhDesc: "从同人小志长出来的朋克分支，歌词直面性向与身份政治，编曲经常带甜的旋律，与硬核场景既并肩又对抗。",
    enDesc: "A punk branch grown out of zines, lyrics facing sexuality and identity head-on, often with sweet melodies — alongside the hardcore scene and against it.",
    key: "Team Dresch — Personal Best",
  },
  {
    id: "no-wave",
    en: "No Wave",
    zh: "无浪潮",
    whereZh: "美国 · 纽约 · 1970s 末",
    whereEn: "New York, USA · late 1970s",
    zhDesc: "彻底否掉摇滚语法：吉他调成非常规音、萨克斯乱吹、节奏刻意生硬，短暫却把后来的噪音摇滚全部预告完了。",
    enDesc: "Rock grammar refused outright: guitars in invented tunings, saxophones flailing, rhythms deliberately stiff — brief, and it forecast everything noisy that followed.",
    key: "V/A — No New York",
  },
  {
    id: "mutant-disco",
    en: "Mutant Disco",
    zh: "变种迪斯科",
    whereZh: "美国 · 纽约 · 1980s 初",
    whereEn: "New York, USA · early 1980s",
    zhDesc: "无浪潮的人去跳舞：迪斯科的律动混进朋克的态度、拉丁打击与荒腔走板的唱腔，怪、扭、但极其好跳。",
    enDesc: "The no wave crowd going dancing: disco groove crossed with punk attitude, Latin percussion and off-key singing — crooked and extremely danceable.",
    key: "V/A — Mutant Disco: A Subtle Discolation of the Norm",
  },
  {
    id: "coldwave",
    en: "Coldwave",
    zh: "冷浪潮",
    whereZh: "法国与比利时 · 1980s",
    whereEn: "France & Belgium · 1980s",
    zhDesc: "欧陆版的 post-punk：鼓机机械地走、贝斯冰冷、法语人声低沉平铺，情绪压抑到几乎不起伏。",
    enDesc: "The continental take on post-punk: drum machines ticking, bass icy, French vocals low and level, emotion pressed almost flat.",
    key: "Trisomie 21 — Passions Divisées",
  },
  {
    id: "minimal-wave",
    en: "Minimal Wave",
    zh: "极简浪潮",
    whereZh: "欧洲 · 1980s",
    whereEn: "Europe · 1980s",
    zhDesc: "卧室里用一台单音合成器和一台鼓机做出的 synth-pop：编曲只剩三层，磁带发行量常常只有几十份，二十年后才被挖出来。",
    enDesc: "Bedroom synth-pop from one monosynth and a drum machine: three layers at most, cassette runs of a few dozen, unearthed twenty years later.",
    key: "V/A — The Minimal Wave Tapes Volume One",
  },
  {
    id: "witch-house",
    en: "Witch House",
    zh: "巫浩室",
    whereZh: "美国 · 2010s 初",
    whereEn: "USA · early 2010s",
    zhDesc: "把 chopped and screwed 的减速手法用在暗色电子上：人声降调发闷、鼓机迟缓、混响厚重，视觉与音乐一起走神秘学路线。",
    enDesc: "Chopped-and-screwed slowing applied to dark electronics: vocals pitched down and muffled, sluggish drum machines, heavy reverb, occult imagery to match.",
    key: "Salem — King Night",
  },
  {
    id: "cloud-rap",
    en: "Cloud Rap",
    zh: "云端说唱",
    whereZh: "美国 · 奥克兰与网络 · 2010s 初",
    whereEn: "Oakland & the internet · early 2010s",
    zhDesc: "beat 由飘忽的合成器与失焦采样铺成，鼓点轻、混音朦胧，说唱像在半梦里自言自语，最早靠 SoundCloud 与博客扩散。",
    enDesc: "Beats of hazy synths and out-of-focus samples, light drums and blurred mixes, rapping half-dreamt aloud — spread first by SoundCloud and blogs.",
    key: "Main Attrakionz — 808s & Dark Grapes II",
  },
  {
    id: "memphis-phonk",
    en: "Memphis Rap (Phonk Source)",
    zh: "孟菲斯磁带说唱",
    whereZh: "美国 · 孟菲斯 · 1990s",
    whereEn: "Memphis, USA · 1990s",
    zhDesc: "自录磁带上的低保真说唱：808 闷响、阴森的合成器循环、双声道都糊在一起，日后被 phonk 整批挖出来当母本。",
    enDesc: "Lo-fi rap off self-dubbed cassettes: muffled 808s, sinister synth loops, both channels smeared together — later mined wholesale as phonk's source material.",
    key: "Tommy Wright III — On the Run",
  },
  {
    id: "drift-phonk",
    en: "Drift Phonk",
    zh: "飘移放克",
    whereZh: "俄罗斯与网络 · 2020s",
    whereEn: "Russia & the internet · 2020s",
    zhDesc: "把孟菲斯磁带采样接上失真到爆的 cowbell 与超饱和 808，节奏直冲，配着漂移赛车视频在短视频平台上疯长。",
    enDesc: "Memphis tape samples wired to blown-out cowbells and oversaturated 808s, driving straight ahead — grown huge on short-video platforms beside drift-car footage.",
    key: "Kordhell — \"Murder in My Mind\"",
  },
  {
    id: "chopped-and-screwed",
    en: "Chopped And Screwed",
    zh: "减速切碎",
    whereZh: "美国 · 休斯顿 · 1990s",
    whereEn: "Houston, USA · 1990s",
    zhDesc: "把整张唱片放慢到六成速度再手动跳针重复：人声变成低沉的拖长句，时间被拉开，专为休斯顿的车内慢驾而生。",
    enDesc: "Whole records slowed to about 60 percent and hand-skipped into repeats: voices dragged low, time pulled apart — made for slow driving in Houston.",
    key: "DJ Screw — Chapter 12: June 27th",
  },
  {
    id: "trap-metal",
    en: "Trap Metal",
    zh: "陷阱金属",
    whereZh: "美国 · 佛罗里达 · 2010s",
    whereEn: "Florida, USA · 2010s",
    zhDesc: "trap 的鼓组配上失真吉他与嘶喊：结构还是说唱，能量与录音质感来自 hardcore，人声常整段推到破音。",
    enDesc: "Trap drums under distorted guitar and screaming: rap structure with hardcore energy and mixing, vocals routinely pushed past clipping.",
    key: "Ghostemane — N/O/I/S/E",
  },
  {
    id: "uk-drill",
    en: "UK Drill",
    zh: "英式钻头说唱",
    whereZh: "英国 · 南伦敦 · 2010s",
    whereEn: "South London, UK · 2010s",
    zhDesc: "把芝加哥 drill 的阴郁搬到伦敦，鼓组换成滑音低音与 140 拍的 hi-hat 碎步，唱腔冷淡、押韵密，气氛紧到发闷。",
    enDesc: "Chicago drill's gloom moved to London: sliding bass and 140 BPM hat shuffles, delivery deadpan, rhymes dense, atmosphere airless.",
    key: "67 — Glorious Twelfth",
  },
  {
    id: "chicago-drill",
    en: "Chicago Drill",
    zh: "芝加哥钻头说唱",
    whereZh: "美国 · 芝加哥南区 · 2010s 初",
    whereEn: "South Side Chicago, USA · early 2010s",
    zhDesc: "慢速 trap 的骨架配上单调阴冷的合成器，说唱平铺直叙地讲街区实况，混音干、留白多，几乎不做任何修饰。",
    enDesc: "Slow trap frames under monotone icy synths, rapping reporting the block flatly, mixes dry and sparse with almost no ornament.",
    key: "King Louie — Dope & Shrimp",
  },
  {
    id: "hyphy",
    en: "Hyphy",
    zh: "亢奋",
    whereZh: "美国 · 湾区 · 2000s",
    whereEn: "Bay Area, USA · 2000s",
    zhDesc: "湾区的派对说唱：贝斯线弹跳、节奏偏快、喊话式副歌，一切为了车队聚会与「去傻」那种放开的状态。",
    enDesc: "Bay Area party rap: springy bass lines, quick tempos, shouted hooks — all aimed at sideshows and the license to act foolish.",
    key: "Mac Dre — Ronald Dregan: Dreganomics",
  },
  {
    id: "jerkin",
    en: "Jerkin'",
    zh: "杰克舞说唱",
    whereZh: "美国 · 洛杉矶 · 2000s 末",
    whereEn: "Los Angeles, USA · late 2000s",
    zhDesc: "为一套舞步写的青少年说唱：合成器简单跳跃、鼓点轻脆、速度偏快，最早靠 YouTube 的舞蹈视频在校园里传开。",
    enDesc: "Teen rap written for one dance: simple bouncing synths, light crisp drums, quick tempo — spread through YouTube dance clips.",
    key: "New Boyz — \"You're a Jerk\"",
  },
  {
    id: "sp1200-boom-bap",
    en: "SP-1200 Boom Bap",
    zh: "SP-1200 低保真说唱",
    whereZh: "美国 · 纽约 · 1990s 初",
    whereEn: "New York, USA · early 1990s",
    zhDesc: "受采样机内存所限，每段采样只有几秒：爵士唱片被切成极短的循环，12 位量化把声音磨出砂纸感，鼓点压得又闷又厚。",
    enDesc: "Sampler memory capped each grab at a few seconds: jazz records cut into tiny loops, 12-bit quantisation sanding the sound, drums thick and muffled.",
    key: "Godfather Don — Hazardous",
  },
  {
    id: "experimental-hip-hop",
    en: "Experimental Hip-Hop",
    zh: "实验说唱",
    whereZh: "美国 · 洛杉矶 · 2010s",
    whereEn: "Los Angeles, USA · 2010s",
    zhDesc: "beat 用工业噪音、无调打击与静默做成，说唱在其中保持精确的节奏感，题材常带政治与叙事野心。",
    enDesc: "Beats built from industrial noise, atonal percussion and silence, with rapping holding precise time — and lyrics carrying political and narrative ambition.",
    key: "clipping. — Midcity",
  },
  {
    id: "mallsoft",
    en: "Mallsoft",
    zh: "商场氛围",
    whereZh: "网络 · 2010s",
    whereEn: "The internet · 2010s",
    zhDesc: "vaporwave 里最空旷的一支：把商场背景乐拉长、加满混响，人声与旋律都退到很远，只剩下空调声与走廊的回音。",
    enDesc: "Vaporwave's emptiest branch: mall muzak stretched and drowned in reverb, melody receding until only air conditioning and corridor echo remain.",
    key: "猫 シ Corp. — Palm Mall",
  },
  {
    id: "future-funk",
    en: "Future Funk",
    zh: "未来放克",
    whereZh: "网络 · 2010s",
    whereEn: "The internet · 2010s",
    zhDesc: "把日本 city pop 与 disco 的片段切成四四拍的循环，加滤波、提速，配上老动画画面，是 vaporwave 里最欢快的一支。",
    enDesc: "Japanese city pop and disco chopped into four-four loops, filtered and sped up, paired with old anime footage — vaporwave's cheerful cousin.",
    key: "Macross 82-99 — Sailorwave",
  },
  {
    id: "dariacore",
    en: "Dariacore",
    zh: "达里亚核",
    whereZh: "网络 · 2020s 初",
    whereEn: "The internet · early 2020s",
    zhDesc: "把流行歌片段以每几秒一次的频率互相撞在一起，jersey club 的鼓型撑底，密度大到像刷短视频时的注意力本身。",
    enDesc: "Pop fragments crashed into each other every few seconds over jersey club drums — density that mimics the attention span it was made for.",
    key: "Leroy — Dariacore",
  },
  {
    id: "digicore",
    en: "Digicore / Glitchcore",
    zh: "数字核",
    whereZh: "网络 · 2020s",
    whereEn: "The internet · 2020s",
    zhDesc: "在卧室里用破解软件做的 hyperpop 分支：吉他采样、失真 808、auto-tune 全部推到红线，情绪直白得像日记。",
    enDesc: "A hyperpop branch made in bedrooms on cracked software: guitar samples, distorted 808s and auto-tune all in the red, feelings as plain as a diary.",
    key: "Jane Remover — Frailty",
  },
  {
    id: "nightcore",
    en: "Nightcore",
    zh: "夜核",
    whereZh: "挪威 · 2000s 初",
    whereEn: "Norway · early 2000s",
    zhDesc: "起初只是两个高中生把 trance 提速变调做成的混音集，人声变尖、节奏变急，二十年后成了整个网络的加速美学源头。",
    enDesc: "It began as two high-schoolers speeding up and pitching trance mixes; twenty years on, that squeaked, hurried sound is the internet's sped-up aesthetic.",
    key: "Nightcore — Energized",
  },
  {
    id: "hypnagogic-pop",
    en: "Hypnagogic Pop",
    zh: "半梦流行",
    whereZh: "美国 · 2000s 末",
    whereEn: "USA · late 2000s",
    zhDesc: "用第四代翻录磁带的音质重写八十年代电台流行：旋律记得住，音源全是霉味，像在别人记忆里听一首没听过的老歌。",
    enDesc: "1980s radio pop rewritten at fourth-generation cassette quality: hummable tunes made of mould — an unheard oldie inside someone else's memory.",
    key: "Ariel Pink's Haunted Graffiti — The Doldrums",
  },
  {
    id: "shitgaze",
    en: "Shitgaze",
    zh: "劣质瞪鞋",
    whereZh: "美国 · 俄亥俄 · 2000s",
    whereEn: "Ohio, USA · 2000s",
    zhDesc: "把流行旋律埋在爆掉的四轨录音里：吉他全是毛刺、人声隔着一层墙，越难听清越显得亲密。",
    enDesc: "Pop melodies buried in blown-out four-track recordings: guitars all burr, vocals behind a wall — the harder to make out, the more intimate.",
    key: "Psychedelic Horseshit — Magic Flowers Droned",
  },
  {
    id: "rage-beats",
    en: "Rage",
    zh: "狂怒说唱",
    whereZh: "美国 · 2020s",
    whereEn: "USA · 2020s",
    zhDesc: "beat 只留两样东西：一条像电锯的合成器与压到失真的 808，说唱把词咬碎成情绪，现场以推挤起跳为默认反应。",
    enDesc: "Beats keep two things — a chainsaw synth and 808s pushed to distortion — while the rapping breaks words into pure affect; moshing is the default response.",
    key: "Playboi Carti — Whole Lotta Red",
  },
  {
    id: "wonky",
    en: "Wonky / Instrumental Beat Scene",
    zh: "歪拍器乐说唱",
    whereZh: "美国 · 洛杉矶 · 2000s 末",
    whereEn: "Los Angeles, USA · late 2000s",
    zhDesc: "刻意把量化关掉：鼓点前后打晃、贝斯音准微微飘，整首听着像喝醉的 hip-hop，源头是洛杉矶的 Low End Theory 夜。",
    enDesc: "Quantisation switched off on purpose: drums wobbling around the grid, bass pitch drifting — drunk hip-hop, born at LA's Low End Theory nights.",
    key: "Flying Lotus — Los Angeles",
  },
];
