/* VprGrid 风格介绍库·世界与根源半：地域传统、民间与非英语流行脉络。
   与 genres-net.js 合并去重后供新标签页的风格卡片抽取。 */

export const GENRES_WORLD = [
  {
    id: "city-pop",
    en: "City Pop",
    zh: "都会流行",
    whereZh: "日本 · 东京 · 1970s–80s",
    whereEn: "Tokyo, Japan · 1970s–80s",
    zhDesc: "泡沫年代录音棚里堆出来的高保真软摇滚，滑顺的电钢、切分吉他和一线乐手的贝斯线，唱的都是夜间高速、海滨公路和不会兑现的约会。",
    enDesc: "Bubble-era Tokyo studio pop: glossy electric piano, chicken-scratch guitar, session-grade basslines, all pointed at night drives and coastal highways.",
    key: "Tatsuro Yamashita — For You",
  },
  {
    id: "shibuya-kei",
    en: "Shibuya-Kei",
    zh: "涩谷系",
    whereZh: "日本 · 涩谷 · 1990s",
    whereEn: "Shibuya, Tokyo · 1990s",
    zhDesc: "唱片店店员做出来的音乐，法国香颂、六十年代电影配乐和 bossa nova 的碎片被拼成甜腻的拼贴，编曲精致到像橱窗陈设。",
    enDesc: "Record-store-clerk pop from Shibuya: French chanson, sixties soundtracks and bossa nova cut up into sweet, boutique-precise collages.",
    key: "Pizzicato Five — Made in USA",
  },
  {
    id: "kayokyoku",
    en: "Kayōkyoku",
    zh: "歌谣曲",
    whereZh: "日本 · 1950s–70s",
    whereEn: "Japan · 1950s–70s",
    zhDesc: "战后唱片工业的主干，西洋管弦与爵士和声套在日语旋律上，编曲豪华、唱腔端正，是演歌与流行分家之前的中间地带。",
    enDesc: "Postwar Japanese record-industry pop: Western orchestras and jazz harmony under Japanese melody, before enka and J-pop split apart.",
    key: "Hibari Misora — \"Kanashii Sake\"",
  },
  {
    id: "enka",
    en: "Enka",
    zh: "演歌",
    whereZh: "日本 · 1960s–80s",
    whereEn: "Japan · 1960s–80s",
    zhDesc: "颤音拖得极长的悲情演唱，五声音阶配上弦乐与三味线，唱港口、雪国、酒和留不住的人，眼泪都在唱法的转折处。",
    enDesc: "Heavy-vibrato Japanese torch singing over pentatonic strings and shamisen: harbours, snow country, sake and people who left.",
    key: "Harumi Miyako — \"Kita no Yado kara\"",
  },
  {
    id: "tsugaru-shamisen",
    en: "Tsugaru-Jamisen",
    zh: "津轻三味线",
    whereZh: "日本 · 青森 · 传统",
    whereEn: "Aomori, Japan · traditional",
    zhDesc: "北国盲人艺人乞食街头留下的粗犷奏法，拨子重砸琴皮，打击与旋律同出一手，即兴段落越比越狠，像刀锋刮过雪面。",
    enDesc: "Percussive northern Japanese lute style from blind itinerant players: the plectrum slams the skin, improvised passages turn into duels.",
    key: "Takahashi Chikuzan — Chikuzan no Sekai",
  },
  {
    id: "min-yo-okinawa",
    en: "Okinawan Min'yō",
    zh: "冲绳民谣",
    whereZh: "日本 · 冲绳 · 传统",
    whereEn: "Okinawa, Japan · traditional",
    zhDesc: "蛇皮三线弹出独特的琉球音阶，缺了两个音于是听着既明亮又悬空，唱段配着拍手与尖锐的呼喊，喜庆里藏着战后的伤。",
    enDesc: "Snakeskin sanshin and the gapped Ryukyuan scale: bright yet unresolved songs, hand claps and piercing calls, wartime grief under the festivity.",
    key: "Shoukichi Kina — Bloodline",
  },
  {
    id: "shakuhachi-honkyoku",
    en: "Shakuhachi Honkyoku",
    zh: "尺八本曲",
    whereZh: "日本 · 传统",
    whereEn: "Japan · traditional",
    zhDesc: "禅僧当作修行的独奏竹笛曲，一口气就是一个乐句，气声、滑音和长静默比音高更重要，听上去更像呼吸而非旋律。",
    enDesc: "Solo bamboo-flute pieces played as Zen practice: one breath per phrase, where breath noise, bends and silence matter more than pitch.",
    key: "Watazumi Doso — Mysterious Sounds of the Japanese Bamboo Flute",
  },
  {
    id: "gagaku",
    en: "Gagaku",
    zh: "雅乐",
    whereZh: "日本 · 宫廷 · 传统",
    whereEn: "Japanese imperial court · traditional",
    zhDesc: "千年未断的宫廷合奏，笙撑出静止的和音层，篳篥在上面极慢地弯音，鼓点相隔数秒落下，时间几乎被拉平。",
    enDesc: "Millennium-old Japanese court ensemble: shō mouth-organ drones, hichiriki reeds bending slowly above, drum strokes seconds apart.",
    key: "Kyoto Imperial Court Music Orchestra — Gagaku: Ancient Japanese Court Music",
  },
  {
    id: "pansori",
    en: "Pansori",
    zh: "盘索里",
    whereZh: "朝鲜半岛 · 传统",
    whereEn: "Korea · traditional",
    zhDesc: "一个歌者一个鼓手撑起数小时的叙事长篇，嗓子练到刻意沙哑破裂，唱念交替，鼓手在缝隙里插进吆喝助兴。",
    enDesc: "Hours-long Korean epic narrative for one singer and one drummer: deliberately roughened voice alternating song and speech, drummer shouting encouragement.",
    key: "Kim So-hee — Chunhyangga",
  },
  {
    id: "sanjo",
    en: "Sanjo",
    zh: "散调",
    whereZh: "朝鲜半岛 · 1900s 前后",
    whereEn: "Korea · around 1900s",
    zhDesc: "为伽倻琴或玄鹤琴写的独奏组曲，从极慢的板式一路加速到密集的收尾，弦被推弯出颤抖的余音，鼓只在骨节处应答。",
    enDesc: "Korean solo zither suites that accelerate from a near-static opening to a dense finish, strings pushed into quavering bends, drum answering at the joints.",
    key: "Hwang Byungki — Kayagum Masterpieces",
  },
  {
    id: "samulnori",
    en: "Samulnori",
    zh: "四物打击",
    whereZh: "韩国 · 首尔 · 1970s",
    whereEn: "Seoul, South Korea · 1970s",
    zhDesc: "把农乐的露天游行搬上舞台的四件打击乐，小锣、鼓、长鼓与大锣层层错位，节拍循环反复推挤，听久了像被卷进漩涡。",
    enDesc: "Four Korean percussion instruments moved from village processions onto the stage: interlocking gongs and drums, cycles pushing until the pulse becomes a vortex.",
    key: "SamulNori — Record of Changes",
  },
  {
    id: "trot",
    en: "Trot",
    zh: "特罗特",
    whereZh: "韩国 · 1960s–80s",
    whereEn: "South Korea · 1960s–80s",
    zhDesc: "踩着二拍子的老派韩国流行，手风琴和电子琴摇摆着走，唱腔带滑音与哭腔，是酒席、长途巴士和中年人的点歌单。",
    enDesc: "Old-school Korean pop on a duple shuffle: accordion and organ swinging, sobbing vocal slides, the songbook of banquets and long bus rides.",
    key: "Lee Mi-ja — \"Camellia Lady\"",
  },
  {
    id: "cantonese-opera",
    en: "Cantonese Opera",
    zh: "粤剧",
    whereZh: "中国 · 广东 · 传统",
    whereEn: "Guangdong, China · traditional",
    zhDesc: "高胯子嗓与椰胡、秦琴、锣鼓一同上行，念白与唱段之间靠板眼衔接，二十世纪的戏班还把小提琴与萨克斯搬上了台。",
    enDesc: "High-strung Cantonese singing over coconut fiddle, plucked lutes and clattering gongs; twentieth-century troupes also dragged violin and saxophone onstage.",
    key: "Hong Xiannü — \"Lizhi Song\"",
  },
  {
    id: "nanyin-nanguan",
    en: "Nanyin / Nanguan",
    zh: "南音",
    whereZh: "中国 · 泉州与台湾 · 传统",
    whereEn: "Quanzhou & Taiwan · traditional",
    zhDesc: "泉州一带留下的极慢室内乐，横抱的琵琶、洞箫与拍板托着女声，一个字能唱出好几拍，听着像宋元的语速还没改过来。",
    enDesc: "Extremely slow chamber song from Quanzhou: horizontally held pipa, end-blown flute and clappers behind a voice that stretches one syllable over bars.",
    key: "Tsai Hsiao-Yueh — Nan-kouan: Chant courtois de la Chine du Sud",
  },
  {
    id: "jiangnan-sizhu",
    en: "Jiangnan Sizhu",
    zh: "江南丝竹",
    whereZh: "中国 · 江浙沪 · 传统",
    whereEn: "Jiangnan, China · traditional",
    zhDesc: "茶馆里几位熟人围坐，二胡、笛、琵琶、扬琴各自给同一条骨干旋律加花，谁多绕一圈别人就让一让，热闹却不抢。",
    enDesc: "Teahouse chamber music from the Yangtze delta: fiddle, flute, pipa and hammered zither each ornament the same skeletal tune, weaving without collision.",
    key: "V/A — Chine: Jiangnan Sizhu (Ocora)",
  },
  {
    id: "guqin",
    en: "Guqin",
    zh: "古琴",
    whereZh: "中国 · 传统",
    whereEn: "China · traditional",
    zhDesc: "七弦琴独奏，音量小得几乎只够弹给自己听，泛音、按滑与指甲擦弦的杂音都算内容，乐句之间的空白比音更长。",
    enDesc: "Solo seven-string zither played almost too quietly to share: harmonics, sliding stops and fingernail scrape all count, silences longer than the notes.",
    key: "Guan Pinghu — \"Liu Shui\"",
  },
  {
    id: "urtiin-duu",
    en: "Urtiin Duu (Long Song)",
    zh: "蒙古长调",
    whereZh: "蒙古与内蒙古 · 传统",
    whereEn: "Mongolia & Inner Mongolia · traditional",
    zhDesc: "一句歌词能拉开几十秒，嗓子在高音区连续做细密装饰，马头琴在下面若有若无地跟着，像草原上望不到边的地平线。",
    enDesc: "One line of text stretched across half a minute, the voice ornamenting high in its range while horsehead fiddle trails behind like an endless horizon.",
    key: "Namjilyn Norovbanzad — \"Uyakhan Zambuu Tiviin Naran\"",
  },
  {
    id: "khoomei",
    en: "Khöömei (Tuvan Throat Singing)",
    zh: "图瓦呼麦",
    whereZh: "俄罗斯 · 图瓦 · 传统",
    whereEn: "Tuva, Russia · traditional",
    zhDesc: "一个人同时发出低音持续与上方哨状泛音，模仿的是马蹄、风与河水，配上弓弦乐器与马蹄节奏，牧歌里带着金属光。",
    enDesc: "One throat producing a low drone plus whistling overtones, imitating hooves, wind and river, set against bowed fiddles and a riding pulse.",
    key: "Huun-Huur-Tu — 60 Horses in My Herd",
  },
  {
    id: "gyuto-chant",
    en: "Gyütö Tantric Chant",
    zh: "藏传密宗诵经",
    whereZh: "西藏与流亡寺院 · 传统",
    whereEn: "Tibet & exile monasteries · traditional",
    zhDesc: "僧人用超低的喉音齐诵，每个人嗓子里同时响出基音与和音，长号与铙钹偶尔炸开一下，声音贴着地面铺过来。",
    enDesc: "Monks chanting in impossibly low multiphonic voices, each throat sounding a chord at once, long horns and cymbals erupting through the floor-level drone.",
    key: "The Gyuto Monks — Tibetan Tantric Choir",
  },
  {
    id: "xibeifeng",
    en: "Xibeifeng (Northwest Wind)",
    zh: "西北风",
    whereZh: "中国 · 1980s",
    whereEn: "Mainland China · 1980s",
    zhDesc: "把陕北信天游的高腔嗓子塞进合成器与电鼓的八十年代内地流行，唱黄土、出走与不甘，粗声大气得像对着山谷喊。",
    enDesc: "Late-eighties mainland pop that dropped Shaanxi highland holler vocals onto synths and drum machines: loess, leaving home, shouting at a valley.",
    key: "Cheng Lin — \"Xintianyou\"",
  },
  {
    id: "luk-thung",
    en: "Luk Thung",
    zh: "泰国乡村歌",
    whereZh: "泰国 · 1960s–70s",
    whereEn: "Thailand · 1960s–70s",
    zhDesc: "农村听众的点唱主力，唱腔满是慢颤音与滑音，伴奏却是电风琴、铜管和拉丁节奏，题材永远绕着离乡进城打工。",
    enDesc: "Thailand's rural hit music: heavily bent, slow-vibrato vocals over farfisa organ, brass and Latin rhythms, forever about leaving the village for the city.",
    key: "V/A — The Sound of Siam: Leftfield Luk Thung, Jazz & Molam from Thailand 1964–75",
  },
  {
    id: "mor-lam",
    en: "Mor Lam",
    zh: "摩兰",
    whereZh: "泰国 · 伊森与老挝 · 传统至 1970s",
    whereEn: "Isan, Thailand & Laos · traditional–1970s",
    zhDesc: "老挝语系的说唱式吟唱，khaen 竹排笙一路不停吹持续和声，歌手押韵斗嘴、连珠炮似地推进，后来接上电贝斯就更催。",
    enDesc: "Lao-language rhyming chant driven by the khaen mouth-organ drone: singers duel in rapid-fire verse, later plugged into electric bass and drums.",
    key: "Angkanang Kunchai — Isan Lam Plearn",
  },
  {
    id: "phleng-phuea-chiwit",
    en: "Phleng Phuea Chiwit",
    zh: "为生命之歌",
    whereZh: "泰国 · 1970s",
    whereEn: "Thailand · 1970s",
    zhDesc: "学生运动年代长出来的抗议民谣，木吉他与泰式笛子并排，歌词替农民和水牛说话，曾被军政府查禁，后来成了大学生宿舍里的经典。",
    enDesc: "Thai protest folk born from the seventies student movement: acoustic guitars beside reed flutes, songs for farmers and buffalo, once banned outright.",
    key: "Caravan — \"Khon Kap Khwai\"",
  },
  {
    id: "cambodian-psych-rock",
    en: "Cambodian Psychedelic Rock",
    zh: "柬埔寨迷幻摇滚",
    whereZh: "柬埔寨 · 金边 · 1960s–70s",
    whereEn: "Phnom Penh, Cambodia · 1960s–70s",
    zhDesc: "美军电台带来的冲浪吉他与灵魂乐节奏，被套上高棉旋律与颤抖的女声，录音在赤柬到来前中断，留下的母带没剩几盘。",
    enDesc: "Surf guitar and soul grooves off American forces radio, wrapped in Khmer melody and quavering female vocals, cut short when the Khmer Rouge arrived.",
    key: "Ros Serey Sothea — \"Chnam Oun Dop-Chet Chnam\"",
  },
  {
    id: "pinpeat",
    en: "Pinpeat",
    zh: "柬埔寨宫廷乐",
    whereZh: "柬埔寨 · 宫廷与寺院 · 传统",
    whereEn: "Cambodian court & temple · traditional",
    zhDesc: "为宫廷舞与影偶戏伴奏的排琴与锣组，硬槌敲出闪亮的颗粒，双簧管在上方滑行，鼓与拍板把整套编制钉在一条缓慢的循环上。",
    enDesc: "Khmer court ensemble of tuned xylophones and gong circles behind masked dance: glittering hard-mallet attacks, a reed gliding above, drums pinning the cycle.",
    key: "V/A — Music of Cambodia Vol. 2: Royal Court Music",
  },
  {
    id: "keroncong",
    en: "Keroncong",
    zh: "克隆钟",
    whereZh: "印尼 · 爪哇 · 1920s–60s",
    whereEn: "Java, Indonesia · 1920s–60s",
    zhDesc: "葡萄牙水手留下的小吉他在爪哇变成一对互咬的拨弦，大提琴用手拨当鼓点，长笛绕着女声打转，摇晃得像旧留声机。",
    enDesc: "Portuguese sailors' small guitars reborn in Java as interlocking plucked patterns, pizzicato cello as drum, flute circling a wavering voice.",
    key: "Gesang — \"Bengawan Solo\"",
  },
  {
    id: "dangdut",
    en: "Dangdut",
    zh: "当都",
    whereZh: "印尼 · 1970s",
    whereEn: "Indonesia · 1970s",
    zhDesc: "名字就来自手鼓那两声「当—嘟」，印度电影歌的滑音、马来班顿与摇滚吉他挤在一起，是集市与竞选舞台上最响的东西。",
    enDesc: "Named after its two drum strokes: Bollywood-style vocal slides, Malay song forms and rock guitar, the loudest thing at any Indonesian market or rally.",
    key: "Rhoma Irama — Begadang",
  },
  {
    id: "jaipongan",
    en: "Jaipongan",
    zh: "嘉伊蓬",
    whereZh: "印尼 · 西爪哇 · 1970s",
    whereEn: "West Java, Indonesia · 1970s",
    zhDesc: "巽他鼓手把村里舞乐改成炸裂的独奏语言，kendang 突然抽拍、猛砸、留白，女声在上面盘旋，舞者只能盯着鼓走。",
    enDesc: "Sundanese drummers rebuilt village dance music as explosive solo language: kendang cutting, slamming and dropping out while a woman's voice circles above.",
    key: "Idjah Hadidjah — Tonggeret",
  },
  {
    id: "gong-kebyar",
    en: "Gong Kebyar",
    zh: "巴厘闪耀甘美兰",
    whereZh: "印尼 · 巴厘 · 1910s 起",
    whereEn: "Bali, Indonesia · from the 1910s",
    zhDesc: "整团青铜乐器同时爆出一击再骤然收住，成对调音让音色抖动不止，快段落由两组交错敲出，速度比单人手速更快。",
    enDesc: "A whole bronze orchestra flashing on one stroke then cutting dead; paired detuning makes the tone shimmer, interlocking parts outrun any single pair of hands.",
    key: "V/A — The Roots of Gamelan: The First Recordings, Bali 1928",
  },
  {
    id: "ca-tru",
    en: "Ca Trù",
    zh: "越南歌筹",
    whereZh: "越南 · 北部 · 传统",
    whereEn: "Northern Vietnam · traditional",
    zhDesc: "女歌者一手敲小竹板，三弦琴稀疏应和，鼓客用一记鼓点当评语；唱腔咬字极紧，颤音像喉咙里含着一根细线。",
    enDesc: "A woman singer clacking bamboo sticks, a three-string lute answering sparsely, a listener's drum stroke as critique; taut diction, wire-thin vibrato.",
    key: "Quách Thị Hồ — Vietnam: Ca Trù & Quan Ho (UNESCO Collection)",
  },
  {
    id: "nhac-vang",
    en: "Nhạc Vàng",
    zh: "黄色音乐",
    whereZh: "越南 · 西贡 · 1960s–70s",
    whereEn: "Saigon, Vietnam · 1960s–70s",
    zhDesc: "西贡时代的慢板情歌，bolero 节奏配电风琴与弦乐，男声带哭腔地唱边城、离别与等不到的信，战后被禁多年仍靠翻录流传。",
    enDesc: "Saigon-era slow ballads on a bolero lilt: organ, strings and sobbing male voices singing garrison towns and letters that never came; banned for decades.",
    key: "Chế Linh — \"Thành Phố Buồn\"",
  },
  {
    id: "kundiman",
    en: "Kundiman",
    zh: "菲律宾情歌体",
    whereZh: "菲律宾 · 1900s–40s",
    whereEn: "Philippines · 1900s–40s",
    zhDesc: "三拍子的他加禄语求爱歌，前半段小调后半段转大调，表面唱女子，殖民年代里大家都听得出唱的是国家。",
    enDesc: "Triple-meter Tagalog courtship song that turns from minor to major halfway: ostensibly to a woman, understood under colonial rule as a song to the nation.",
    key: "Nicanor Abelardo — \"Mutya ng Pasig\"",
  },
  {
    id: "manila-sound",
    en: "Manila Sound",
    zh: "马尼拉之声",
    whereZh: "菲律宾 · 马尼拉 · 1970s",
    whereEn: "Manila, Philippines · 1970s",
    zhDesc: "马科斯戒严年代的轻快本地流行，软摇滚与灵魂乐底子上唱起街头菲式英语混搭，歌词笑嘻嘻地写通勤、追女生和吃饭。",
    enDesc: "Breezy local pop from martial-law Manila: soft-rock and soul grooves with cheerful Taglish lyrics about commuting, crushes and where to eat.",
    key: "Hotdog — Unang Kagat",
  },
  {
    id: "mahagita",
    en: "Mahāgīta (Burmese Harp Song)",
    zh: "缅甸古典歌乐",
    whereZh: "缅甸 · 宫廷传统",
    whereEn: "Burmese court tradition · traditional",
    zhDesc: "船形弯琴 saung 与歌者互相追逐，琴弦调得松，音一出来就往下垂，拍板点出不规则的强弱，旋律听着总像刚要落地又飘开。",
    enDesc: "The boat-shaped Burmese harp chasing a singer over slack strings that sag as they sound, bell and clapper marking an off-kilter beat.",
    key: "Inle Myint Maung & Yi Yi Thant — Mahāgīta: Harp and Vocal Music of Burma",
  },
  {
    id: "baul",
    en: "Baul",
    zh: "包尔游吟",
    whereZh: "印度与孟加拉 · 孟加拉地区 · 传统",
    whereEn: "Bengal, India & Bangladesh · traditional",
    zhDesc: "不属任何教派的游方歌者，一手弹单弦 ektara，脚踝系铃铛，歌词用身体与河流比喻神，边走边唱，嗓子沙得像风吹过芦苇。",
    enDesc: "Wandering Bengali mystics outside every sect: one-string ektara, ankle bells, songs using body and river as metaphors for god, voices raw as reed wind.",
    key: "Purna Das Baul — The Bauls of Bengal",
  },
  {
    id: "manganiyar",
    en: "Manganiyar",
    zh: "曼加尼亚尔",
    whereZh: "印度 · 拉贾斯坦沙漠 · 传统",
    whereEn: "Rajasthan desert, India · traditional",
    zhDesc: "沙漠里的世袭乐师家族，替资助的贵族家唱婚丧与家谱，kamaicha 弓弦低吟，khartal 木板打得极碎，嗓门横着推出去。",
    enDesc: "Hereditary desert musicians singing weddings, deaths and patrons' genealogies: growling kamaicha fiddle, clattering wooden khartal, voices pushed wide open.",
    key: "V/A — Rajasthan: Musiciens professionnels populaires (Ocora)",
  },
  {
    id: "thumri",
    en: "Thumri",
    zh: "图姆里",
    whereZh: "印度 · 北方邦 · 1800s–1900s",
    whereEn: "Uttar Pradesh, India · 1800s–1900s",
    zhDesc: "北印古典里最放得开的抒情体裁，一句情话可以翻着花腔唱十分钟，规矩让位给语气，听的是歌者怎么把一个字揉软。",
    enDesc: "The most pliant lyric form in Hindustani classical: a single line of longing spun for ten minutes, rules giving way to how a syllable is bent.",
    key: "Bade Ghulam Ali Khan — \"Yaad Piya Ki Aaye\"",
  },
  {
    id: "dhrupad",
    en: "Dhrupad",
    zh: "德鲁帕德",
    whereZh: "印度 · 宫廷传统",
    whereEn: "North Indian court tradition · traditional",
    zhDesc: "北印古典中最古老最朴素的一支，没有花俏装饰，先用无节拍的长段把一个调的骨架慢慢立起来，pakhawaj 鼓晚半小时才进来。",
    enDesc: "The oldest, austerest branch of Hindustani music: no filigree, a vast unmetered exposition raising the raga's skeleton before the pakhawaj drum enters.",
    key: "Ustad Zia Mohiuddin Dagar — Raga Yaman",
  },
  {
    id: "filmi-funk",
    en: "Filmi Funk",
    zh: "宝莱坞放克",
    whereZh: "印度 · 孟买 · 1970s",
    whereEn: "Bombay, India · 1970s",
    zhDesc: "孟买配乐棚里把摩格合成器、瓦瓦吉他和迪斯科弦乐塞进歌舞场面，印度旋律照唱，底下的槽却是当年最时髦的舞池节奏。",
    enDesc: "Bombay soundtrack rooms loading Moog, wah guitar and disco strings under dance numbers: Indian melody on top, the decade's hottest groove beneath.",
    key: "R. D. Burman — Shalimar",
  },
  {
    id: "lollywood-soundtrack",
    en: "Lollywood Soundtrack Pop",
    zh: "拉合尔影歌",
    whereZh: "巴基斯坦 · 拉合尔 · 1970s",
    whereEn: "Lahore, Pakistan · 1970s",
    zhDesc: "巴基斯坦影业的配乐棚风格，乌尔都语情歌上叠电风琴、失真吉他与手鼓，预算紧、混音生猛，粗糙处反而成了它的招牌。",
    enDesc: "Pakistani film-studio pop: Urdu love songs over cheap organ, distorted guitar and tabla, mixed hot on tiny budgets until the roughness became the sound.",
    key: "V/A — The Sound of Wonder! (Pakistani film music, Finders Keepers)",
  },
  {
    id: "ghazal-urdu",
    en: "Urdu Ghazal Singing",
    zh: "乌尔都加扎尔",
    whereZh: "巴基斯坦与北印度 · 1960s–80s",
    whereEn: "Pakistan & North India · 1960s–80s",
    zhDesc: "把古典诗的对句唱成半即兴的独唱，harmonium 与 sarangi 只在底下托着，歌者把同一句词换好几种腔反复唱，留出的停顿正好给听众叹气。",
    enDesc: "Classical Urdu couplets sung half-improvised over harmonium and sarangi, the singer recasting one line several ways and pausing for the audience's sigh.",
    key: "Mehdi Hassan — \"Ranjish Hi Sahi\"",
  },
  {
    id: "sufi-kafi",
    en: "Sufi Kafi",
    zh: "苏菲卡菲",
    whereZh: "巴基斯坦 · 旁遮普与信德 · 传统",
    whereEn: "Punjab & Sindh, Pakistan · traditional",
    zhDesc: "唱布雷沙等苏菲诗人的旁遮普语诗，一句叠句反复上推直到嗓子撕开，手鼓与 harmonium 跟着加速，属于圣墓前的通宵场合。",
    enDesc: "Punjabi verses of Sufi poets like Bulleh Shah, a refrain pushed upward until the voice tears, tabla and harmonium accelerating at all-night shrine gatherings.",
    key: "Abida Parveen — \"Tere Ishq Nachaya\"",
  },
  {
    id: "tarab",
    en: "Tarab",
    zh: "塔拉布",
    whereZh: "埃及 · 开罗 · 1930s–60s",
    whereEn: "Cairo, Egypt · 1930s–60s",
    zhDesc: "大型阿拉伯管弦为独唱者铺路，一首能唱一小时，歌者反复回到同一句上加花，台下听众的喝彩本身就是乐曲的一部分。",
    enDesc: "Large Arabic orchestras clearing the way for one singer across an hour, returning again and again to one line while the audience's cries become part of the piece.",
    key: "Umm Kulthum — \"Alf Leila wa Leila\"",
  },
  {
    id: "qudud-halabiyya",
    en: "Qudud Halabiyya",
    zh: "阿勒颇古都德",
    whereZh: "叙利亚 · 阿勒颇 · 传统",
    whereEn: "Aleppo, Syria · traditional",
    zhDesc: "阿勒颇的老城歌本，宗教与世俗歌词共用同一批曲调，男声合唱与独唱轮替，拍子突然转换，听得出苏菲聚会里的身体摆动。",
    enDesc: "Aleppo's old-city songbook where sacred and secular texts share tunes: soloist alternating with male chorus, meters switching, Sufi sway audible underneath.",
    key: "Sabah Fakhri — \"Ya Mal al-Sham\"",
  },
  {
    id: "andalusi-nuba",
    en: "Andalusi Nuba",
    zh: "安达卢斯努巴",
    whereZh: "摩洛哥与阿尔及利亚 · 传统",
    whereEn: "Morocco & Algeria · traditional",
    zhDesc: "摩尔人被逐出伊比利亚后带走的组曲传统，一套按固定节奏序列从慢到快走完，齐唱与 rebab、乌德交错，规模大得像一场仪式。",
    enDesc: "Suite tradition carried out of Iberia by exiled Moors: fixed rhythmic movements running slow to fast, unison chorus trading with rebab and oud.",
    key: "Ustad Massano Tazi — Musique classique andalouse de Fès",
  },
  {
    id: "chaabi-algiers",
    en: "Chaabi (Algiers)",
    zh: "阿尔及尔沙比",
    whereZh: "阿尔及利亚 · 阿尔及尔老城 · 1930s–70s",
    whereEn: "Casbah of Algiers · 1930s–70s",
    zhDesc: "老城咖啡馆里长出的市井歌乐，mandole 领奏，段落越走越急，唱移民、赌运与酒，后来成了巴黎阿尔及利亚人乡愁的声音。",
    enDesc: "Casbah café music led by the mandole, sections gathering speed across a long song about migration, luck and drink — later the anthem of Algerians in Paris.",
    key: "Dahmane El Harrachi — \"Ya Rayah\"",
  },
  {
    id: "gnawa",
    en: "Gnawa",
    zh: "格纳瓦",
    whereZh: "摩洛哥 · 传统",
    whereEn: "Morocco · traditional",
    zhDesc: "撒哈拉以南奴隶后裔的通灵仪式乐，三弦低音琴 guembri 顶着铁响板 qraqeb，整夜按颜色分段推进，把人推到出神为止。",
    enDesc: "Trance ritual music of Moroccans descended from sub-Saharan slaves: booming three-string guembri under iron qraqeb, all-night suites ordered by colour.",
    key: "Maleem Mahmoud Ghania with Pharoah Sanders — The Trance of Seven Colors",
  },
  {
    id: "dabke-syria",
    en: "Syrian Keyboard Dabke",
    zh: "叙利亚键盘达布卡",
    whereZh: "叙利亚 · 哈塞克 · 1990s",
    whereEn: "Hassake, Syria · 1990s",
    zhDesc: "婚礼现场把踏步舞曲交给一台调过音准的电子琴，模仿 mijwiz 芦笛的尖锐音色狂扫，主唱在扩音器里吼着现编的祝词。",
    enDesc: "Wedding dabke handed to one retuned keyboard imitating shrieking mijwiz reeds, while the singer bellows improvised blessings straight into the PA.",
    key: "Omar Souleyman — Highway to Hassake: Folk and Pop Sounds of Syria",
  },
  {
    id: "persian-radif",
    en: "Persian Radif",
    zh: "波斯拉迪夫",
    whereZh: "伊朗 · 传统",
    whereEn: "Iran · traditional",
    zhDesc: "师徒口传的曲目体系，一套 dastgāh 按规定次序展开，santur 或 tar 与歌者一句一句应答，几乎没有固定节拍，全靠呼吸。",
    enDesc: "An orally transmitted repertoire unfolding a dastgāh in fixed order: santur or tar answering the singer phrase by phrase, pulse governed only by breath.",
    key: "Mohammad Reza Shajarian & Parviz Meshkatian — Bidad",
  },
  {
    id: "mugham",
    en: "Mugham",
    zh: "阿塞拜疆木卡姆",
    whereZh: "阿塞拜疆 · 传统",
    whereEn: "Azerbaijan · traditional",
    zhDesc: "歌者一手摇着框鼓，tar 与 kamancha 在旁托着，情绪层层往上顶，到高处近乎呜咽，中间插进短小的固定歌调喘口气。",
    enDesc: "A singer beating a frame drum while tar and kamancha hold the ground, emotion climbing toward a near-sob, brief fixed songs dropped in to breathe.",
    key: "Alim & Fargana Qasimov — Spiritual Music of Azerbaijan",
  },
  {
    id: "arabesk",
    en: "Arabesk",
    zh: "阿拉贝斯克",
    whereZh: "土耳其 · 1970s–80s",
    whereEn: "Turkey · 1970s–80s",
    zhDesc: "进城打工者的哭腔流行，阿拉伯式弦乐群与 bağlama 加上电吉他，歌词全是被骗、被抛下与命不好，被精英骂了几十年。",
    enDesc: "Weeping pop of Turkey's rural migrants: Arabic-style string swells, bağlama and electric guitar behind lyrics of betrayal and bad fate, scorned by elites.",
    key: "Orhan Gencebay — \"Batsın Bu Dünya\"",
  },
  {
    id: "anadolu-psych",
    en: "Anadolu Psych",
    zh: "安纳托利亚迷幻",
    whereZh: "土耳其 · 伊斯坦布尔 · 1970s",
    whereEn: "Istanbul, Turkey · 1970s",
    zhDesc: "把民谣的微分音旋律交给加了效果器的电吉他和电 saz，鼓组照西方摇滚打，结果既是摇滚又保留了村里舞曲的不对称拍。",
    enDesc: "Folk melodies with their microtonal bends handed to fuzzed guitar and electric saz over a Western rock kit, village dance meters left crooked.",
    key: "Erkin Koray — Elektronik Türküler",
  },
  {
    id: "asik-tradition",
    en: "Âşık Tradition",
    zh: "阿希克吟游",
    whereZh: "土耳其 · 安纳托利亚 · 传统",
    whereEn: "Anatolia, Turkey · traditional",
    zhDesc: "自弹 saz 自唱的游吟诗人，讲道理也讲故事，还常两人对垒即兴押韵；曲调朴素到几乎只剩说话的起伏，重量全在词上。",
    enDesc: "Anatolian bards accompanying themselves on saz, preaching and storytelling and duelling in improvised rhyme, melodies stripped to speech contour.",
    key: "Aşık Veysel — \"Uzun İnce Bir Yoldayım\"",
  },
  {
    id: "shashmaqam",
    en: "Shashmaqam",
    zh: "六木卡姆",
    whereZh: "乌兹别克与塔吉克 · 布哈拉 · 传统",
    whereEn: "Bukhara, Uzbekistan & Tajikistan · traditional",
    zhDesc: "布哈拉宫廷与犹太乐师共同守住的六套大曲，从器乐段进入声乐段，音区一路往上爬，到顶点时嗓子几乎绷断。",
    enDesc: "Six courtly suites kept alive by Bukharan Muslim and Jewish musicians alike: instrumental sections giving way to vocal cycles that climb until the voice strains.",
    key: "V/A — Bukhara: Musical Crossroads of Asia",
  },
  {
    id: "uyghur-muqam",
    en: "Uyghur Muqam",
    zh: "维吾尔木卡姆",
    whereZh: "中国 · 新疆 · 传统",
    whereEn: "Xinjiang, China · traditional",
    zhDesc: "长达数小时的组曲，从自由吟唱开头，逐步接入 satar 长颈弓弦与手鼓的舞段，节拍越换越密，最后变成整村跟着跳。",
    enDesc: "Hours-long Uyghur suites opening in free recitation, then folding in long-necked satar and frame drums as meters tighten into village-wide dancing.",
    key: "V/A — Turkestan chinois/Xinjiang: musiques ouïgoures (Ocora)",
  },
  {
    id: "komuz-kyrgyz",
    en: "Kyrgyz Komuz Music",
    zh: "柯尔克孜库姆兹",
    whereZh: "吉尔吉斯斯坦 · 传统",
    whereEn: "Kyrgyzstan · traditional",
    zhDesc: "三弦无品琴的独奏小品，乐手边弹边把琴翻转抛接，旋律模拟马步与鸟叫，一段器乐曲往往附带一整个传说。",
    enDesc: "Solo pieces for the fretless three-string komuz, flipped and tossed mid-performance, melodies imitating horse gaits and birds, each tune carrying a legend.",
    key: "Tengir-Too — Music of Central Asia Vol. 1: Mountain Music of Kyrgyzstan",
  },
  {
    id: "falak",
    en: "Falak",
    zh: "帕米尔法拉克",
    whereZh: "塔吉克斯坦 · 巴达赫尚 · 传统",
    whereEn: "Badakhshan, Tajikistan · traditional",
    zhDesc: "帕米尔山区的哀歌体，唱命运与离别，嗓子拉到极高再往下滑，rubab 与框鼓稀疏应答，常在葬礼与长夜聚会上唱。",
    enDesc: "Pamiri lament on fate and separation: the voice hauled to its ceiling then slid down, rubab and frame drum answering sparsely at funerals and long nights.",
    key: "V/A — Music of Central Asia Vol. 5: The Badakhshan Ensemble",
  },
  {
    id: "palm-wine-highlife",
    en: "Palm-Wine Highlife",
    zh: "棕榈酒吉他",
    whereZh: "西非 · 沿海港口 · 1950s–60s",
    whereEn: "Coastal West Africa · 1950s–60s",
    zhDesc: "酒棚里一把吉他一个手鼓的松散唱段，指法是水手带来的葡语弹法与本地节奏对上的产物，速度慢、话多、笑点也多。",
    enDesc: "One guitar, one hand drum and a long loose song in a drinking bar: sailors' Lusophone fingerpicking married to coastal rhythm, slow, chatty and wry.",
    key: "S.E. Rogie — Palm Wine Guitar Music: The 60's Sound",
  },
  {
    id: "burger-highlife",
    en: "Burger Highlife",
    zh: "汉堡高生活",
    whereZh: "加纳与德国 · 1980s",
    whereEn: "Ghana & Germany · 1980s",
    zhDesc: "移居德国的加纳乐手用多轨棚和合成器重做高生活，吉他线路照旧交错，底下换成打点清亮的电鼓，气味介于阿克拉与迪斯科。",
    enDesc: "Ghanaian musicians in Germany rebuilt highlife with synths and multitrack: the interlocking guitars stayed, the bottom became crisp drum machine and disco sheen.",
    key: "George Darko — \"Akoo Te Brofo\"",
  },
  {
    id: "fuji",
    en: "Fújì",
    zh: "富吉",
    whereZh: "尼日利亚 · 拉各斯 · 1970s–80s",
    whereEn: "Lagos, Nigeria · 1970s–80s",
    zhDesc: "从斋月唤醒歌发展成的纯打击乐流派，一堆会说话的鼓与铁片，没有和弦乐器，主唱靠夸赞与斗嘴撑起一整面，现场能开到通宵。",
    enDesc: "Grown from Ramadan wake-up songs into an all-percussion style: talking drums and iron bells, no chords, a praise-singer carrying whole sides till dawn.",
    key: "Sikiru Ayinde Barrister — Fuji Garbage",
  },
  {
    id: "apala",
    en: "Apala",
    zh: "阿帕拉",
    whereZh: "尼日利亚 · 约鲁巴地区 · 1950s–70s",
    whereEn: "Yorubaland, Nigeria · 1950s–70s",
    zhDesc: "手鼓与拇指琴般的金属摩擦声配上低沉的约鲁巴语劝世词，速度不快但拍子极黏，唱的是道德、人情与社交场上的谁欠谁。",
    enDesc: "Yoruba hand drums and scraped metal under low proverbial singing: unhurried but sticky rhythm, lyrics weighing morals, favours and social debts.",
    key: "Haruna Ishola — Oroki Social Club",
  },
  {
    id: "ethio-jazz",
    en: "Ethio-Jazz",
    zh: "埃塞爵士",
    whereZh: "埃塞俄比亚 · 亚的斯亚贝巴 · 1960s–70s",
    whereEn: "Addis Ababa, Ethiopia · 1960s–70s",
    zhDesc: "把埃塞俄比亚五声调式塞进爵士与拉丁编制，颤音琴与管乐吹出偏斜的音阶，听着既像纽约后台也像亚的斯的夜总会。",
    enDesc: "Ethiopian pentatonic modes loaded into jazz and Latin arrangements: vibraphone and horns leaning on skewed scales, half New York, half Addis nightclub.",
    key: "Mulatu Astatke — Éthiopiques 4: Ethio Jazz & Musique Instrumentale",
  },
  {
    id: "azmari",
    en: "Azmari",
    zh: "阿兹马里",
    whereZh: "埃塞俄比亚 · 传统至 1990s",
    whereEn: "Ethiopia · traditional–1990s",
    zhDesc: "酒馆里的即兴歌手，拉着单弦 masenqo 或弹 krar，词是当场编的双关与讽刺，谁给钱就唱谁，也顺便把政治藏在情话里。",
    enDesc: "Tavern improvisers on one-string masenqo or krar, inventing punning satire on the spot, flattering whoever pays and hiding politics inside love talk.",
    key: "V/A — Éthiopiques 2: Tètchawèt! Urban Azmaris of the 90's",
  },
  {
    id: "tuareg-assouf",
    en: "Tuareg Assouf",
    zh: "图阿雷格漠地吉他",
    whereZh: "撒哈拉 · 马里与阿尔及利亚 · 1980s 起",
    whereEn: "Sahara, Mali & Algeria · from the 1980s",
    zhDesc: "流亡营地里靠电吉他与手鼓写成的歌，循环乐句慢慢咬住不放，合唱与拍手垫底，唱思乡、枪与骆驼道上的漫长等待。",
    enDesc: "Songs written in exile camps on electric guitar and hand drum: circling riffs that refuse to resolve, chorused answers, homesickness, rifles, long desert waits.",
    key: "Tinariwen — Amassakoul",
  },
  {
    id: "wassoulou",
    en: "Wassoulou",
    zh: "瓦苏鲁",
    whereZh: "马里 · 南部 · 1980s–90s",
    whereEn: "Southern Mali · 1980s–90s",
    zhDesc: "马里南部的女声主导传统，六弦猎人竖琴 kamale ngoni 与葫芦打击铺底，歌词直说婚姻、生育与女人的处境，嗓子不留退路。",
    enDesc: "Woman-led tradition from southern Mali over hunters' six-string kamale ngoni and gourd percussion, lyrics naming marriage, childbearing and women's lot outright.",
    key: "Oumou Sangaré — Moussolou",
  },
  {
    id: "jeliya",
    en: "Jeliya (Kora Tradition)",
    zh: "世袭乐师之艺",
    whereZh: "西非 · 曼德地区 · 传统",
    whereEn: "Mande West Africa · traditional",
    zhDesc: "世袭乐师家族掌管的历史记忆，二十一弦竖琴 kora 双手分工，右手滚花左手守骨干，唱段之间插进整段家族谱系的念诵。",
    enDesc: "Hereditary Mande musicians holding the historical record: the 21-string kora's right hand spinning figures over a left-hand ostinato, genealogies recited between verses.",
    key: "Toumani Diabaté — Kaira",
  },
  {
    id: "sabar",
    en: "Sabar",
    zh: "萨巴鼓乐",
    whereZh: "塞内加尔 · 传统",
    whereEn: "Senegal · traditional",
    zhDesc: "沃洛夫人的鼓群，一手木棒一手手掌，鼓语能对应具体句子，众鼓齐鸣时突然停在一个空拍上，舞者就靠那一拍炸出动作。",
    enDesc: "Wolof drum ensembles played with one stick and one hand, strokes spelling actual phrases, the whole battery stopping on an empty beat for a dancer's explosion.",
    key: "Doudou N'Diaye Rose — Djabote",
  },
  {
    id: "bikutsi",
    en: "Bikutsi",
    zh: "比库齐",
    whereZh: "喀麦隆 · 雅温得 · 1980s",
    whereEn: "Yaoundé, Cameroon · 1980s",
    zhDesc: "把贝提人木琴敲击搬到电吉他上，弦被调得又薄又脆，节拍是往地上踩的三拍循环，歌词直白得让当年的电台不太敢放。",
    enDesc: "Beti xylophone patterns transplanted to thin, brittle electric guitar over a stamping triple-time cycle, with lyrics blunt enough to worry state radio.",
    key: "Les Têtes Brulées — Hot Heads",
  },
  {
    id: "kwassa-kwassa",
    en: "Kwassa Kwassa",
    zh: "夸萨夸萨",
    whereZh: "刚果与巴黎 · 1980s",
    whereEn: "Congo & Paris · 1980s",
    zhDesc: "刚果伦巴提速后的舞厅版本，前半段唱情歌，后半段整曲交给吉他的 sebene 循环，越弹越快，吆喝声一句接一句往上垫。",
    enDesc: "Congolese rumba sped up for the dancefloor: a sung half, then the guitar sebene taking the whole track over, accelerating under stacked shouted calls.",
    key: "Kanda Bongo Man — Kwassa Kwassa",
  },
  {
    id: "guinean-authenticite",
    en: "Guinean Authenticité Orchestras",
    zh: "几内亚国家乐团",
    whereZh: "几内亚 · 科纳克里 · 1960s–70s",
    whereEn: "Conakry, Guinea · 1960s–70s",
    zhDesc: "国营乐团奉命把古老的曼德史诗改编成大编制电声乐队，管乐与双吉他齐奏 kora 的乐句，一首曲子能横跨整面唱片。",
    enDesc: "State-funded bands ordered to rework ancient Mande epics for electric orchestra: horns and twin guitars doubling kora lines across whole LP sides.",
    key: "Bembeya Jazz National — Regard sur le Passé",
  },
  {
    id: "benga",
    en: "Benga",
    zh: "本加",
    whereZh: "肯尼亚 · 卢奥地区 · 1960s–80s",
    whereEn: "Luo Kenya · 1960s–80s",
    zhDesc: "把卢奥人竖琴 nyatiti 的跳跃低音搬给电吉他与贝斯，两把吉他交错跑得飞快，段落末尾转调像换了个房间。",
    enDesc: "The leaping bass of the Luo nyatiti lyre handed to guitar and electric bass: two guitars racing in interlock, each section shifting key like changing rooms.",
    key: "D.O. Misiani & Shirati Jazz — Benga Blast!",
  },
  {
    id: "taarab",
    en: "Taarab",
    zh: "桑给巴尔塔拉布",
    whereZh: "坦桑尼亚 · 桑给巴尔 · 1900s–80s",
    whereEn: "Zanzibar, Tanzania · 1900s–80s",
    zhDesc: "印度洋港口的混血歌乐，阿拉伯乌德、埃及式弦乐群与斯瓦希里语诗并置，唱得含蓄，暗讽藏在比喻里，婚宴上一句能扎人一年。",
    enDesc: "Indian Ocean port music: Arabic oud, Egyptian-style string section and Swahili verse, insults hidden in metaphor and aimed across the wedding hall.",
    key: "Ikhwani Safaa Musical Club — Music of Zanzibar: Taarab 4",
  },
  {
    id: "marrabenta",
    en: "Marrabenta",
    zh: "马拉本塔",
    whereZh: "莫桑比克 · 马普托 · 1950s–80s",
    whereEn: "Maputo, Mozambique · 1950s–80s",
    zhDesc: "郊区用铁丝和罐头自制吉他弹出来的舞曲，节奏轻快偏赶，唱词是葡语殖民末期的市井笑话，独立后被扩编成整支电声乐团。",
    enDesc: "Dance music first played on guitars built from tin and wire in Maputo's suburbs: hurried, skipping rhythm and street humour, later scaled up to an electric orchestra.",
    key: "Orchestra Marrabenta Star de Moçambique — Independance",
  },
  {
    id: "mbira-dzavadzimu",
    en: "Mbira Dzavadzimu",
    zh: "祖灵姆比拉",
    whereZh: "津巴布韦 · 绍纳地区 · 传统",
    whereEn: "Shona Zimbabwe · traditional",
    zhDesc: "装在葫芦共鸣箱里的拇指琴，金属片上串着瓶盖发出沙响，循环乐句几十分钟不变，通灵仪式上靠它把祖先的声音叫回来。",
    enDesc: "Thumb piano in a gourd resonator, bottle caps buzzing against the keys, one cycle held for half an hour to call ancestral spirits into a possession ceremony.",
    key: "Stella Chiweshe — Ambuya?",
  },
  {
    id: "mbaqanga",
    en: "Mbaqanga",
    zh: "姆巴甘加",
    whereZh: "南非 · 约翰内斯堡 · 1960s–80s",
    whereEn: "Johannesburg, South Africa · 1960s–80s",
    zhDesc: "城镇录音棚的流水线舞曲，贝斯线粗壮跳跃，女声三重唱在上方齐唱，男主唱用极低的「咆哮」嗓插话，三分钟一首毫不拖延。",
    enDesc: "Assembly-line township dance music: thick loping bass, a female trio harmonising above, and a groaning bass-voiced man answering, all inside three minutes.",
    key: "Mahlathini & the Mahotella Queens — Thokozile",
  },
  {
    id: "maskandi",
    en: "Maskandi",
    zh: "马斯坎迪",
    whereZh: "南非 · 夸祖鲁 · 1970s 起",
    whereEn: "KwaZulu, South Africa · from the 1970s",
    zhDesc: "祖鲁旅人吉他弹唱，指法带着 ukupika 的滚动，歌中间要插一段飞快的自我介绍式念白，报出姓氏、村名与恩怨。",
    enDesc: "Zulu travelling guitar song with rolling ukupika picking, interrupted midway by a rapid spoken boast naming the singer's clan, village and grudges.",
    key: "Shiyani Ngcobo — Introducing Shiyani Ngcobo",
  },
  {
    id: "cape-jazz",
    en: "Cape Jazz",
    zh: "开普爵士",
    whereZh: "南非 · 开普敦 · 1970s",
    whereEn: "Cape Town, South Africa · 1970s",
    zhDesc: "开普敦的爵士方言，把游行队伍的 goema 节奏和教会和声塞进钢琴左手，旋律简单反复，在种族隔离年代成了半公开的国歌。",
    enDesc: "Cape Town's jazz dialect: carnival goema rhythm and church harmony pressed into the piano's left hand, a simple repeated tune that became an underground anthem.",
    key: "Abdullah Ibrahim — \"Mannenberg\"",
  },
  {
    id: "funana",
    en: "Funaná",
    zh: "富纳纳",
    whereZh: "佛得角 · 圣地亚哥岛 · 传统至 1990s",
    whereEn: "Santiago, Cape Verde · traditional–1990s",
    zhDesc: "一台手风琴对一根刮铁片，两个人就能把舞会撑到天亮，节奏往前赶得几乎要翻掉，殖民当局嫌它太野蛮曾长期禁演。",
    enDesc: "One accordion against one scraped iron bar keeping a dance going till dawn, the rhythm rushing forward — banned for years by colonial authorities as too crude.",
    key: "Bitori — Legend of Funaná",
  },
  {
    id: "morna",
    en: "Morna",
    zh: "莫尔纳",
    whereZh: "佛得角 · 1930s–90s",
    whereEn: "Cape Verde · 1930s–90s",
    zhDesc: "群岛的慢摇情歌，吉他与 cavaquinho 摆出懒散的摆荡，克里奥尔语唱的全是离岛、思念与回不去的码头，克制得不肯哭出来。",
    enDesc: "Slow creole island song swaying on guitar and cavaquinho, every lyric about emigration and a harbour you can't return to, too restrained to actually weep.",
    key: "Cesária Évora — Miss Perfumado",
  },
  {
    id: "maloya",
    en: "Maloya",
    zh: "马洛亚",
    whereZh: "法国 · 留尼汪岛 · 传统",
    whereEn: "Réunion · traditional",
    zhDesc: "奴隶后裔的祖灵歌舞，大框鼓 roulèr 坐着敲，竹筒摇出细密沙响，领唱与合唱一来一往，拍子偏得让人第一次听会数错。",
    enDesc: "Ancestor-summoning song and dance of Réunion's slave descendants: a seated roulèr drum, rattling bamboo, call and response over a beat that trips first-time listeners.",
    key: "Danyèl Waro — Foutan Fonnkèr",
  },
  {
    id: "chicha",
    en: "Chicha (Amazonian Cumbia)",
    zh: "亚马逊奇查",
    whereZh: "秘鲁 · 亚马逊油镇 · 1960s–70s",
    whereEn: "Peruvian Amazon oil towns · 1960s–70s",
    zhDesc: "石油小镇的舞会音乐，冲浪吉他与颤音效果器套在哥伦比亚 cumbia 的两拍上，安第斯五声旋律与电风琴互相顶，热得发潮。",
    enDesc: "Oil-boom dance music from jungle towns: surf guitar and tremolo laid on a Colombian cumbia pulse, Andean pentatonic tunes trading with farfisa organ.",
    key: "Los Mirlos — \"Sonido Amazónico\"",
  },
  {
    id: "huayno",
    en: "Huayno",
    zh: "瓦伊诺",
    whereZh: "秘鲁与玻利维亚 · 安第斯 · 传统",
    whereEn: "Andes, Peru & Bolivia · traditional",
    zhDesc: "安第斯高原的对舞歌，竖琴或小提琴领着一个短促的跳跃节奏走，女声尖细高亢，歌词在克丘亚语与西语之间来回跳。",
    enDesc: "Andean couple-dance song driven by harp or fiddle on a short skipping rhythm, with piercing high female voices sliding between Quechua and Spanish.",
    key: "V/A — Huayno Music of Peru Vol. 1 (Arhoolie)",
  },
  {
    id: "chacarera",
    en: "Chacarera",
    zh: "查卡雷拉",
    whereZh: "阿根廷 · 圣地亚哥德尔埃斯特罗 · 传统",
    whereEn: "Santiago del Estero, Argentina · traditional",
    zhDesc: "内陆干旱省份的舞歌，吉他扫弦与 bombo 大鼓踩着六拍与三拍的双重感觉，歌词混着克丘亚土语，唱干活、干旱与解闷的酒。",
    enDesc: "Dance song from Argentina's dry interior: strummed guitar and bombo drum straddling six and three at once, lyrics salted with Quechua words.",
    key: "Atahualpa Yupanqui — \"Chacarera de las Piedras\"",
  },
  {
    id: "changui",
    en: "Changüí",
    zh: "昌桂",
    whereZh: "古巴 · 关塔那摩 · 传统",
    whereEn: "Guantánamo, Cuba · traditional",
    zhDesc: "古巴东部山区的老式派对乐，tres 吉他、marímbula 低音箱与大号 bongó 咬着一个前置的重音，拍子偏得连专业乐手都数错。",
    enDesc: "Old-style party music from Cuba's eastern hills: tres guitar, marímbula bass box and oversized bongó locked on an anticipated accent that trips trained players.",
    key: "V/A — Changüí: The Sound of Guantánamo",
  },
  {
    id: "descarga",
    en: "Descarga",
    zh: "古巴即兴长段",
    whereZh: "古巴 · 哈瓦那 · 1950s",
    whereEn: "Havana, Cuba · 1950s",
    zhDesc: "录音棚里深夜的即兴大会，乐手就着一个两和弦的循环轮流独奏，贝斯不停摆，一卷带子录满就算一首，爵士与舞厅在此打平。",
    enDesc: "After-hours studio jams where players solo in turn over a two-chord vamp, bass never stopping, a take ending when the tape does.",
    key: "Cachao — Cuban Jam Sessions in Miniature: Descargas",
  },
  {
    id: "huapango-huasteco",
    en: "Huapango Huasteco",
    zh: "瓦斯特卡华潘戈",
    whereZh: "墨西哥 · 瓦斯特卡 · 传统",
    whereEn: "Huasteca, Mexico · traditional",
    zhDesc: "三人小组：小提琴拉出大段炫技花腔，两把吉他一高一低垫节奏，两个男声轮流飙到假声破音，越比越高，舞者踩木板应答。",
    enDesc: "Three players: a violin spinning virtuoso figures over high and low guitars while two men trade lines into cracking falsetto, dancers answering on a wooden platform.",
    key: "Los Camperos de Valles — El Triunfo: Sones de la Huasteca",
  },
  {
    id: "conjunto-tejano",
    en: "Conjunto Tejano",
    zh: "德州墨裔手风琴乐",
    whereZh: "美国 · 南德州 · 1930s–80s",
    whereEn: "South Texas, USA · 1930s–80s",
    zhDesc: "德墨边境的舞厅编制，全音阶手风琴对上十二弦低音吉他 bajo sexto，波尔卡与华尔兹的节拍留着德国移民的印子，歌词是西语的。",
    enDesc: "Border dancehall lineup of diatonic accordion against twelve-string bajo sexto, keeping German-immigrant polka and waltz meters under Spanish lyrics.",
    key: "Flaco Jiménez — Ay Te Dejo en San Antonio",
  },
  {
    id: "choro",
    en: "Choro",
    zh: "肖罗",
    whereZh: "巴西 · 里约 · 1900s–60s",
    whereEn: "Rio de Janeiro, Brazil · 1900s–60s",
    zhDesc: "里约的器乐炫技传统，曼陀铃或长笛跑十六分音符不歇气，七弦吉他在低音区顶着反向的对旋律，转调频繁，聚会里轮流较劲。",
    enDesc: "Rio's instrumental virtuoso tradition: mandolin or flute running unbroken sixteenths while a seven-string guitar answers in the bass, keys changing constantly.",
    key: "Jacob do Bandolim — \"Noites Cariocas\"",
  },
  {
    id: "forro-pe-de-serra",
    en: "Forró Pé-De-Serra",
    zh: "山脚福罗",
    whereZh: "巴西 · 东北 · 1940s–60s",
    whereEn: "Northeast Brazil · 1940s–60s",
    zhDesc: "三件乐器就够：手风琴、三角铁与 zabumba 扁鼓，节奏一摇一摆地往前推，唱干旱、迁徙与内地人的骄傲，是六月节的标配。",
    enDesc: "Three instruments suffice — accordion, triangle and zabumba drum — rocking forward under songs of drought, migration and backlands pride at June festivals.",
    key: "Luiz Gonzaga — \"Asa Branca\"",
  },
  {
    id: "samba-rock",
    en: "Samba-Rock",
    zh: "桑巴摇滚",
    whereZh: "巴西 · 圣保罗与里约 · 1960s–70s",
    whereEn: "São Paulo & Rio, Brazil · 1960s–70s",
    zhDesc: "黑人舞会上拿吉他右手切分去撞灵魂乐的鼓点，贝斯线学着放克走，桑巴的摇摆没丢，转身舞步靠那点错位的推进感。",
    enDesc: "Black dance-party music where a slashing samba guitar hand meets a soul drum kit and funk bass, the swing intact and the push deliberately off-centre.",
    key: "Jorge Ben — África Brasil",
  },
  {
    id: "mento",
    en: "Mento",
    zh: "门托",
    whereZh: "牙买加 · 1940s–50s",
    whereEn: "Jamaica · 1940s–50s",
    zhDesc: "牙买加最早的乡村流行，班卓、竹笛、手摇沙锤加一把土制低音，重音落在第四拍，唱的全是荤笑话与乡下八卦，比 ska 还早一辈。",
    enDesc: "Jamaica's first rural pop: banjo, bamboo fife, rumba box and shakers accenting the fourth beat, packed with bawdy jokes a generation before ska.",
    key: "V/A — Take Me to Jamaica: The Story of Jamaican Mento",
  },
  {
    id: "rocksteady",
    en: "Rocksteady",
    zh: "洛克斯代迪",
    whereZh: "牙买加 · 金斯敦 · 1960s",
    whereEn: "Kingston, Jamaica · 1960s",
    zhDesc: "ska 突然放慢下来的那两三年，管乐退场、贝斯线变成主角，和声组唱美国灵魂乐式的情歌，舞步从跳跃改成贴着地磨。",
    enDesc: "The two or three years when ska slowed down: horns receding, bass lines taking the lead, harmony trios singing soul ballads for dancers who stopped jumping.",
    key: "Alton Ellis — Mr. Soul of Jamaica",
  },
  {
    id: "konpa",
    en: "Konpa",
    zh: "康帕",
    whereZh: "海地 · 1950s–70s",
    whereEn: "Haiti · 1950s–70s",
    zhDesc: "海地舞厅的招牌节奏，鼓点平稳得像走路，萨克斯与吉他在上面绕，纽约的海地移民乐队把它加上放克贝斯又送回岛上。",
    enDesc: "Haiti's signature dancehall groove: a walking, unhurried beat under circling saxophones and guitar, later sent home from New York with funk bass attached.",
    key: "Tabou Combo — \"New York City\"",
  },
  {
    id: "mizik-rasin",
    en: "Mizik Rasin",
    zh: "海地根源乐",
    whereZh: "海地 · 太子港 · 1980s–90s",
    whereEn: "Port-au-Prince, Haiti · 1980s–90s",
    zhDesc: "把伏都仪式的鼓与颂歌接上摇滚乐队编制，鼓组三层叠着走，合唱唱神名，八十年代末在独裁末期成了街头抗争的声音。",
    enDesc: "Vodou ceremonial drums and chants plugged into a rock band: three drum layers interlocking, choruses naming spirits, street protest music as the dictatorship fell.",
    key: "Boukman Eksperyans — Vodou Adjae",
  },
  {
    id: "rebetiko",
    en: "Rebetiko",
    zh: "雷贝提卡",
    whereZh: "希腊 · 比雷埃夫斯 · 1920s–40s",
    whereEn: "Piraeus, Greece · 1920s–40s",
    zhDesc: "小亚细亚难民带到港口贫民区的歌，bouzouki 与 baglamas 拨出瘦硬的音色，唱监狱、大麻窝与穷到没辙的日子，节拍常是九拍。",
    enDesc: "Songs of Asia Minor refugees in port slums: wiry bouzouki and baglamas behind prison, hashish-den and destitution lyrics, often in limping nine-beat meter.",
    key: "Markos Vamvakaris — \"Frankosyriani\"",
  },
  {
    id: "entekhno",
    en: "Éntekhno",
    zh: "希腊艺术歌",
    whereZh: "希腊 · 1960s",
    whereEn: "Greece · 1960s",
    zhDesc: "作曲家给现代诗谱曲，用 bouzouki 与小型管弦把民间节拍抬进音乐厅，唱腔朴素不炫技，独裁年代里被当成政治宣言来听。",
    enDesc: "Composers setting modern Greek poetry, lifting folk meters into the concert hall with bouzouki and small orchestra; plain singing heard as politics under the junta.",
    key: "Mikis Theodorakis — Epitaphios",
  },
  {
    id: "coimbra-fado",
    en: "Coimbra Fado",
    zh: "科英布拉法多",
    whereZh: "葡萄牙 · 科英布拉 · 1950s–60s",
    whereEn: "Coimbra, Portugal · 1950s–60s",
    zhDesc: "大学城的男声传统，只穿黑袍在夜里唱给窗口听，葡萄牙吉他的滑音细如丝，不为钱不鼓掌，后来接上了反抗萨拉查的歌。",
    enDesc: "A university men's tradition sung to windows at night in black capes: silken Portuguese guitar runs, no applause, no pay, later turned against Salazar.",
    key: "José Afonso — Baladas de Coimbra",
  },
  {
    id: "cante-jondo",
    en: "Cante Jondo",
    zh: "深沉之歌",
    whereZh: "西班牙 · 安达卢西亚 · 传统",
    whereEn: "Andalusia, Spain · traditional",
    zhDesc: "弗拉门戈里最沉的几个曲式，siguiriya 与 martinete 几乎不用吉他，只靠喊嗓与铁锤敲拍，一句歌词要唱到嗓子哑掉才算数。",
    enDesc: "The heaviest flamenco forms: siguiriya and martinete need barely any guitar, just a cried-out voice and hammer strokes, one line pushed until the throat frays.",
    key: "V/A — Antología del Cante Flamenco (Hispavox)",
  },
  {
    id: "canzone-napoletana",
    en: "Canzone Napoletana",
    zh: "那不勒斯歌谣",
    whereZh: "意大利 · 那不勒斯 · 1880s–1950s",
    whereEn: "Naples, Italy · 1880s–1950s",
    zhDesc: "那不勒斯方言写的城市歌谣，曼陀铃与吉他托着大跨度的旋律，副歌一上就往高处拉，移民把它随船带到纽约的每个街角。",
    enDesc: "City songs in Neapolitan dialect: mandolin and guitar under wide-arching melodies that leap at the refrain, carried to every immigrant street corner in New York.",
    key: "Roberto Murolo — Napoletana",
  },
  {
    id: "pizzica-salentina",
    en: "Pizzica Salentina",
    zh: "萨伦托皮齐卡",
    whereZh: "意大利 · 萨伦托 · 传统",
    whereEn: "Salento, Italy · traditional",
    zhDesc: "原是给被毒蛛咬过的女人做疗愈仪式的快速舞曲，铃鼓一路加速不肯停，女声尖利，手风琴与提琴跟着转，跳到人瘫下为止。",
    enDesc: "Fast dance once used to cure women bitten by spiders: a tambourine accelerating without mercy, piercing voices, fiddle and accordion circling until dancers drop.",
    key: "Officina Zoè — Sangue Vivo",
  },
  {
    id: "rock-progressivo-italiano",
    en: "Rock Progressivo Italiano",
    zh: "意大利前卫摇滚",
    whereZh: "意大利 · 1970s",
    whereEn: "Italy · 1970s",
    zhDesc: "七十年代意大利乐队把交响乐、教堂管风琴和歌剧式唱腔塞进长篇组曲，转折比英国同行更急，抒情段落甜得不加掩饰。",
    enDesc: "Seventies Italian bands packing symphonic strings, church organ and operatic singing into long suites: sharper turns than their British peers, unashamedly lush.",
    key: "Premiata Forneria Marconi — Per un Amico",
  },
  {
    id: "library-music",
    en: "Library Music",
    zh: "库存音乐",
    whereZh: "英国与意大利 · 1960s–70s",
    whereEn: "UK & Italy · 1960s–70s",
    zhDesc: "专供电视台买断使用的成套录音，一线乐手匿名录制，每首都短、直接、只讲一个情绪，标题就叫「紧张追逐」或「都市清晨」。",
    enDesc: "Albums pressed only for broadcasters to license: anonymous top session players cutting short, on-the-nose cues titled things like \"Tense Chase\" or \"City Morning\".",
    key: "V/A — The Sound Gallery",
  },
  {
    id: "spaghetti-western-score",
    en: "Spaghetti Western Score",
    zh: "意式西部片配乐",
    whereZh: "意大利 · 罗马 · 1960s–70s",
    whereEn: "Rome, Italy · 1960s–70s",
    zhDesc: "罗马配乐棚的独门配器：口哨、电吉他颤音、马鞭响、女高音无词吟唱与教堂钟声并置，为几乎没有台词的对峙镜头造出全部情绪。",
    enDesc: "Rome's scoring rooms invented a palette of whistling, tremolo guitar, whip cracks, wordless soprano and church bells to carry near-wordless standoffs.",
    key: "Ennio Morricone — Il Grande Silenzio",
  },
  {
    id: "bulgarian-wedding-music",
    en: "Bulgarian Wedding Music",
    zh: "保加利亚婚礼乐",
    whereZh: "保加利亚 · 1980s",
    whereEn: "Bulgaria · 1980s",
    zhDesc: "婚宴上的炫技乐队，单簧管与萨克斯把民间不对称拍吹到极速，中段突然拐进爵士和声，当年因太过出格而被文化部门盯上。",
    enDesc: "Wedding bands playing folk odd meters at impossible speed on clarinet and sax, veering into jazz harmony mid-tune — too wild for the culture ministry.",
    key: "Ivo Papasov — Orpheus Ascending",
  },
  {
    id: "balkan-brass",
    en: "Balkan Brass Band",
    zh: "巴尔干铜管",
    whereZh: "塞尔维亚与罗马尼亚 · 传统至 1990s",
    whereEn: "Serbia & Romania · traditional–1990s",
    zhDesc: "罗姆人乐队用旧军乐编制吹村里的舞曲，大号一个人当整个节奏组，小号在上面飙到破音，婚礼上绕着人头吹到你掏钱为止。",
    enDesc: "Roma bands playing village dances on old military brass: one tuba as the whole rhythm section, trumpets screaming above, blown at your ear until you pay up.",
    key: "Fanfare Ciocărlia — Radio Paşcani",
  },
  {
    id: "cantu-a-tenore",
    en: "Cantu A Tenore",
    zh: "撒丁四声部牧歌",
    whereZh: "意大利 · 撒丁岛 · 传统",
    whereEn: "Sardinia, Italy · traditional",
    zhDesc: "四个牧羊人围成一圈，两人用喉音发出粗糙的持续音，像风箱也像羊叫，另两人在上面唱旋律与诗句，和声挤得几乎发涩。",
    enDesc: "Four Sardinian shepherds in a circle: two producing rasping guttural drones like bellows or bleating, two carrying the verse above in bitingly close harmony.",
    key: "Tenores di Bitti — S'Amore 'e Mama",
  },
  {
    id: "georgian-polyphony",
    en: "Georgian Polyphony",
    zh: "格鲁吉亚复调",
    whereZh: "格鲁吉亚 · 传统",
    whereEn: "Georgia · traditional",
    zhDesc: "三声部男声合唱，用的不是西欧律制，于是和弦听着又宽又涩，低音持续不断，上面两声部互相绕行，饭桌上的祝酒歌也这么唱。",
    enDesc: "Three-part male singing outside Western tuning, so the chords ring wide and astringent: a constant bass with two upper voices crossing, sung even as toasts.",
    key: "Rustavi Choir — Georgian Voices",
  },
  {
    id: "russian-bard-song",
    en: "Russian Bard Song",
    zh: "苏联吟游歌",
    whereZh: "苏联 · 1960s–80s",
    whereEn: "Soviet Union · 1960s–80s",
    zhDesc: "一把走音的木吉他，一个嗓子哑掉的作者，词写得比曲重要，靠私录磁带在厨房与登山队之间传抄，官方唱片厂从不发行。",
    enDesc: "One out-of-tune acoustic guitar and a hoarse author whose words outweigh the tune, circulated on home-taped reels through kitchens, never pressed by the state label.",
    key: "Vladimir Vysotsky — \"Koni Priveredlivye\"",
  },
  {
    id: "hawaiian-slack-key",
    en: "Hawaiian Slack-Key Guitar",
    zh: "夏威夷松弦吉他",
    whereZh: "美国 · 夏威夷 · 1900s–70s",
    whereEn: "Hawaii, USA · 1900s–70s",
    zhDesc: "把吉他弦调松成开放和弦，拇指弹低音、其余指头摘出旋律与泛音，家族之间各有秘传调法，歌唱起来常带假声翻转。",
    enDesc: "Guitars slackened into open tunings, thumb walking the bass while fingers pick melody and harmonics; tunings kept as family secrets, vocals flipping into falsetto.",
    key: "The Gabby Pahinui Hawaiian Band — Vol. 1",
  },
  {
    id: "sacred-harp",
    en: "Sacred Harp (Shape-Note)",
    zh: "神圣竖琴谱歌",
    whereZh: "美国 · 南部乡村 · 1800s 起",
    whereEn: "Rural American South · from the 1800s",
    zhDesc: "会众围成方阵面对面齐唱，四声部各占一边，用形状记谱不用乐器，唱得又响又直，声音撞在木墙上散不开，重在一起唱不在好听。",
    enDesc: "Congregations sing in a hollow square, one voice part per side, reading shaped noteheads with no instruments: loud, blunt singing meant for participants, not listeners.",
    key: "V/A — Rivers of Delight: American Folk Hymns from the Sacred Harp Tradition",
  },
  {
    id: "old-time-appalachian",
    en: "Old-Time Appalachian String Band",
    zh: "阿巴拉契亚老式弦乐",
    whereZh: "美国 · 阿巴拉契亚 · 1920s–70s",
    whereEn: "Appalachia, USA · 1920s–70s",
    zhDesc: "提琴与班卓同奏一条旋律，不像蓝草那样轮流独奏，弓法带着刮擦声，节奏为跳舞而生，一首曲子能不换花样地转上五分钟。",
    enDesc: "Fiddle and banjo playing one melody together rather than trading solos: scratchy bowing, dance-driven rhythm, a tune held for five minutes without variation.",
    key: "Tommy Jarrell — Sail Away Ladies",
  },
  {
    id: "cajun-dance-music",
    en: "Cajun Dance Music",
    zh: "卡真舞曲",
    whereZh: "美国 · 路易斯安那 · 1930s–70s",
    whereEn: "Louisiana, USA · 1930s–70s",
    zhDesc: "法语区舞厅的两步与华尔兹，全音阶手风琴与提琴齐头并进，三角铁敲个不停，男声用假声般的高腔硬喊，为的是压过跳舞的脚步声。",
    enDesc: "French-Louisiana two-steps and waltzes: diatonic accordion doubled by fiddle, triangle ringing throughout, vocals pitched high to carry over the dancers' feet.",
    key: "The Balfa Brothers — The Balfa Brothers Play Traditional Cajun Music",
  },
  {
    id: "hill-country-blues",
    en: "Hill Country Blues",
    zh: "丘陵蓝调",
    whereZh: "美国 · 密西西比北部 · 1960s–90s",
    whereEn: "North Mississippi, USA · 1960s–90s",
    zhDesc: "不走十二小节套路的蓝调分支，一个乐句一个和弦就撑满整首，吉他反复推着同一个音型，靠非洲式的鼓点与拍手把人钉在原地摆动。",
    enDesc: "Blues that ignores the twelve-bar form: one riff, one chord, guitar grinding the same figure while drums and hand claps hold dancers in place, swaying.",
    key: "Mississippi Fred McDowell — I Do Not Play No Rock 'n' Roll",
  },
  {
    id: "northern-soul",
    en: "Northern Soul",
    zh: "北方灵魂乐",
    whereZh: "英国 · 英格兰北部 · 1970s",
    whereEn: "Northern England · 1970s",
    zhDesc: "英国北部通宵舞厅挖出来的美国冷门单曲，速度偏快、鼓点顶着四拍猛敲，原唱多半在美国没红过，唱片稀有度本身成了审美。",
    enDesc: "Obscure American soul 45s unearthed for all-nighters in northern England: fast four-on-the-floor stompers that flopped at home, rarity itself becoming the aesthetic.",
    key: "Frank Wilson — \"Do I Love You (Indeed I Do)\"",
  },
];
