/** High-signal experimental / modern-composition / EAI roster for stature scoring. */

const EXACT = new Set(
  [
    "gas",
    "pan",
    "amm",
    "oval",
    "coil",
    "earth",
    "boris",
    "autechre",
    "merzbow",
    "grouper",
    "haino",
    "fennesz",
    "biosphere",
    "deathprod",
    "alva noto",
    "pan sonic",
    "sunn o)))",
    "sunn o))",
  ].map((s) => s.toLowerCase()),
);

const FUZZY = [
  "fennesz",
  "keith rowe",
  "eliane radigue",
  "éliane radigue",
  "jim o'rourke",
  "oren ambarchi",
  "william basinski",
  "tim hecker",
  "stars of the lid",
  "kevin drumm",
  "phill niblock",
  "pauline oliveros",
  "evan parker",
  "john butcher",
  "taku sugimoto",
  "sachiko m",
  "toshimaru nakamura",
  "keith fullerton whitman",
  "aphex twin",
  "boards of canada",
  "venetian snares",
  "oneohtrix point never",
  "the caretaker",
  "leyland kirby",
  "wolfgang voigt",
  "mika vainio",
  "ryuichi sakamoto",
  "nurse with wound",
  "current 93",
  "thomas köner",
  "thomas koner",
  "bj nilsen",
  "chris watson",
  "francisco lópez",
  "francisco lopez",
  "annea lockwood",
  "luc ferrari",
  "pierre henry",
  "pierre schaeffer",
  "iannis xenakis",
  "györgy ligeti",
  "morton feldman",
  "la monte young",
  "tony conrad",
  "charlemagne palestine",
  "sarah davachi",
  "kali malone",
  "ellen arkbro",
  "clarice jensen",
  "huerco s",
  "space afrika",
  "félícia atkinson",
  "felicia atkinson",
  "kassel jaeger",
  "stephen o'malley",
  "natural snow buildings",
  "six organs of admittance",
  "bill orcutt",
  "loren connors",
  "keiji haino",
  "hijokaidan",
  "incapacitants",
  "the dead c",
  "roy montgomery",
  "daniel menche",
  "max corbacho",
  "michiru aoyama",
  "mick chillage",
  "djrum",
  "christoph de babalon",
  "ben frost",
  "fennesz sakamoto",
  "emptyset",
  "raime",
  "demdike stare",
  "shackleton",
  "andy stott",
  "burial",
  "lee gamble",
  "container",
  "helena hauff",
  "kaitlyn aurelia smith",
  "suzanne ciani",
  "laurel halo",
  "jlin",
  "rp boo",
  "arnafóss",
  "anna von hausswolff",
  "swans",
  "michael pisaro",
  "antoine beuger",
  "jürg frey",
  "jurg frey",
  "malfatti",
  "radu malfatti",
  "keith berry",
  "richard chartier",
  "taylor deupree",
  "sawako",
  "chihei hatakeyama",
  "celer",
  "will long",
  "loscil",
  "marsen jules",
  "abul mogard",
  "alessandro cortini",
  "caterina barbieri",
  "rolling clock",
  "lawrence english",
  "benoit pioulard",
  "rafael anton irisarri",
  "alexandre navarro",
  "yann novak",
  "asva",
  "locrian",
  "wolves in the throne room",
  "nathalie stern",
  "marja ahti",
  "johanna sueco",
  "eiko ishioka",
  "akira rabelais",
  "jan jelinek",
  " stephan mathieu",
  "stephan mathieu",
  "mark fell",
  "rhodri davies",
  "angharad davies",
  "john tilbury",
  "eddie prevost",
  "eddie précost",
  "cornelius cardew",
  "derek bailey",
  "evan parker",
  "mats gustafsson",
  "ken vandermark",
  "peter brötzmann",
  "peter brotzmann",
  "han bennink",
  "joe mcphee",
  "nathaniel mackey",
  "moondog",
  "arthur russell",
  "julius eastman",
  "anohni",
  "anya",
  "hildur gudnadottir",
  "johann johannsson",
  "johann jóhannsson",
  "max richter",
  "nils frahm",
  "olafur arnalds",
  "ólfur arnalds",
  "jlin",
  "autechre",
  "aphex",
  "squarepusher",
  "autechre",
  "μ-ziq",
  "u-ziq",
  "bogdan raczynski",
  "the future sound of london",
  "plaid",
  "b12",
  "black dog",
  "autechre",
  "keith fullerton whitman",
  "markus popp",
  "yasunao tone",
  "ryoji ikeda",
  "carsten nicolai",
  "alva noto",
  "byetone",
  "emptyset",
  "ben frost",
  "tim hecker",
  "fennesz",
  "christian fennesz",
  "sakamoto",
  "ryuichi",
  "harper simon",
  "grouper",
  "liz harris",
  "julianna barwick",
  "weyes blood",
  "circuit des yeux",
  "haley fohr",
  "six organs",
  "ben chasny",
  "current 93",
  "david tibet",
  "coil",
  "john balance",
  "peter christopherson",
  "throbbing gristle",
  "psychic tv",
  "nurse with wound",
  "steven stapleton",
  "organum",
  "david jackman",
  "zoviet france",
  " :zoviet*france:",
  "muslimgauze",
  "bryn jones",
  "the shadow ring",
  "graham lambkin",
  "jason lescalleet",
  "aaron dilloway",
  "wolf eyes",
  "john wiese",
  "prurient",
  "dominick fernow",
  "vatican shadow",
  "rainforest spiritual enslavement",
  "the body",
  "full of hell",
  "lingua ignota",
  "kristin hayter",
  "rev. kriss hades",
  "yellow swans",
  "pete swanson",
  "gabriel saloman",
  "burning star core",
  "crescendo",
  "emeralds",
  "oneohtrix",
  "daniel lopatin",
  "james ferraro",
  "ramona lisa",
  "far side virtual",
  "dean blunt",
  "andy stott",
  "demdike",
  "shackleton",
  "actress",
  "darren cunningham",
  "burial",
  "kode9",
  "hyperdub",
  "lee scratch perry",
  "the bug",
  "king midas sound",
  "space afrika",
  "klein",
  "moin",
  "raime",
  "kassel jaeger",
  "francois bonnet",
  "françois bonnet",
  "ina grm",
  "recollection grm",
  "beatriz ferreyra",
  "bernard parmegiani",
  "eliane radigue",
  "ika",
  "oka",
  "akira rabelais",
  "william basinski",
  "disintegration loops",
  "the caretaker",
  "everywhere at the end of time",
  "leyland kirby",
  "philip jeck",
  "janek schaefer",
  "christian marclay",
  "yasunao tone",
  "oval",
  "markus popp",
  "alva noto",
  "ryoji ikeda",
  "pan sonic",
  "mika vainio",
  "ilpo väisänen",
  "ilpo vaisanen",
  "emptyset",
  "senyawa",
  "keiji haino",
  "oren ambarchi",
  "stephen o'malley",
  "attila csihar",
  "sunn",
  "earth",
  "dylan carlson",
  "boris",
  "merzbow",
  "masami akita",
  "hijokaidan",
  "incapacitants",
  "hanatarash",
  "gerogerigegege",
  "masonna",
  "solmania",
  "c.c.c.c.",
  "aube",
  "akifumi nakajima",
  "john duncan",
  "z'ev",
  "boyd rice",
  "non",
  "death in june",
  "current 93",
  "nurse with wound",
  "coil",
  "throbbing gristle",
  "chris watson",
  "jana winderen",
  "david toop",
  "max eastley",
  "annea lockwood",
  "andrea polli",
  "francisco lopez",
  "toshimaru nakamura",
  "sachiko m",
  "otomo yoshihide",
  "tetuzi akiyama",
  "taku unami",
  "seiichi yamamoto",
  "the satanics",
  "ground zero",
  "filament",
  "i.s.o.",
  "keith rowe",
  "john tilbury",
  "eddie prevost",
  "cornelius cardew",
  "scratch orchestra",
  "morton feldman",
  "john cage",
  "christian wolff",
  "earle brown",
  "la monte young",
  "marian zazeela",
  "tony conrad",
  "theatre of eternal music",
  "phill niblock",
  "eliane radigue",
  "pauline oliveros",
  "deep listening",
  "maryanne amacher",
  "alvin lucier",
  "david tudor",
  "gordon mumma",
  "david behrman",
  "robert ashley",
  "julius eastman",
  "arthur russell",
  "moondog",
  "harry partch",
  "conlon nancarrow",
  "gyorgy ligeti",
  "xenakis",
  "stockhausen",
  "pierre boulez",
  "luciano berio",
  "luigi nono",
  "giacinto scelsi",
  "horatiu radulescu",
  "gerard grisey",
  "gérard grisey",
  "tristan murail",
  "kaija saariaho",
  "georg friedrich haas",
  "rebecca saunders",
  "helmut lachenmann",
  "wolfgang rihm",
  "harrison birtwistle",
  "thomas ades",
  "george benjamin",
  "olga neuwirth",
  "unas",
  "sarah davachi",
  "kali malone",
  "ellen arkbro",
  "maria w horn",
  " Caterina barbieri",
  "caterina barbieri",
  "alessandro cortini",
  "rolling clock",
  "nils frahm",
  "olafur arnalds",
  "max richter",
  "johann johannsson",
  "hildur guðnadóttir",
  "hildur gudnadottir",
  "jlin",
  "rp boo",
  "footwork",
  "autechre",
  "aphex twin",
  "richard d james",
  "squarepusher",
  "tom jenkinson",
  "mike paradinas",
  "µ-ziq",
  "planet mu",
  "bogdan raczynski",
  "venetian snares",
  "aaron funk",
  "the future sound of london",
  "plaid",
  "b12",
  "the black dog",
  "boards of canada",
  "mike sandison",
  "marcus eoin",
  "oneohtrix point never",
  "daniel lopatin",
  "james ferraro",
  "far side virtual",
  "ramona lisa",
  "dean blunt",
  "andy stott",
  "demdike stare",
  "shackleton",
  "actress",
  "burial",
  "kode9",
  "the bug",
  "space afrika",
  "klein",
  "moin",
  "raime",
  "empty set",
  "ben frost",
  "tim hecker",
  "fennesz",
  "alva noto",
  "ryoji ikeda",
  "pan sonic",
  "grouper",
  "liz harris",
  "julianna barwick",
  "circuit des yeux",
  "six organs of admittance",
  "natural snow buildings",
  "bill orcutt",
  "loren mazzaCane connors",
  "loren connors",
  "john fahey",
  "robbie basho",
  "fahey",
  "richard youngs",
  "shirley collins",
  "current 93",
  "nurse with wound",
  "coil",
  "chris watson",
  "jana winderen",
  "david toop",
  "annea lockwood",
  "francisco lópez",
  "toshimaru nakamura",
  "sachiko m",
  "otomo yoshihide",
  "keith rowe",
  "john tilbury",
  "morton feldman",
  "john cage",
  "la monte young",
  "tony conrad",
  "phill niblock",
  "éliane radigue",
  "pauline oliveros",
  "alvin lucier",
  "julius eastman",
  "arthur russell",
  "moondog",
  "sarah davachi",
  "kali malone",
  "ellen arkbro",
  "caterina barbieri",
  "nils frahm",
  "max richter",
  "jlin",
  "autechre",
  "aphex twin",
  "squarepusher",
  "boards of canada",
  "oneohtrix point never",
  "actress",
  "burial",
  "tim hecker",
  "fennesz",
  "alva noto",
  "grouper",
  "merzbow",
  "keiji haino",
  "oren ambarchi",
  "stephen o'malley",
  "sun o)))",
  "daniel menche",
  "lawrence english",
  "rafael anton irisarri",
  "loscil",
  "chihei hatakeyama",
  "celer",
  "taylor deupree",
  "richard chartier",
  "mark fell",
  "jan jelinek",
  "stephan mathieu",
  "rhodri davies",
  "angharad davies",
  "mats gustafsson",
  "peter brötzmann",
  "derek bailey",
  "evan parker",
  "john butcher",
  "joe mcphee",
  "ken vandermark",
  "senyawa",
  "wolf eyes",
  "aaron dilloway",
  "graham lambkin",
  "jason lescalleet",
  "prurient",
  "lingva ignota",
  "lingua ignota",
  "yellow swans",
  "emeralds",
  "christian marclay",
  "philip jeck",
  "the caretaker",
  "william basinski",
  "leyland kirby",
  "beatriz ferreyra",
  "bernard parmegiani",
  "kassel jaeger",
  "ina-grm",
  "maryanne amacher",
  "robert ashley",
  "david tudor",
  "harry partch",
  "conlon nancarrow",
  "stockhausen",
  "xenakis",
  "ligeti",
  "scelsi",
  "grisey",
  "murail",
  "saariaho",
  "lachenmann",
  "haas",
  "rebecca saunders",
  "helmut lachenmann",
  "王长存",
  "阎银飞",
  "李剑鸿",
  "torturing nurse",
  "zhaoze",
  "马思唯",
].map((s) => s.trim().toLowerCase()).filter((s) => s.length >= 4);

const FUZZY_SET = new Set(FUZZY);

const LABEL_HINTS = [
  "editions mego",
  "raster-noton",
  "raster noton",
  "touch music",
  "12k",
  "room40",
  "shelter press",
  "black truffle",
  "erstwhile",
  "another timbre",
  "wandelweiser",
  "glistening examples",
  "recital",
  "important records",
  "kranky",
  "constellation",
  "hallow ground",
  "portraits grm",
  "recollection grm",
  "unseen worlds",
  "rvng",
  "warp records",
  "planet mu",
  "hyperdub",
  "pan records",
  "pan ",
  "mego",
  "editions mego",
  "ideal record",
  "iideeal",
  "posh isolation",
  "hospital productions",
  "not not fun",
  "nna tapes",
  "students of decay",
  "spectrum spools",
  "editions mego",
  "touch.",
];

function norm(s: string): string {
  return s
    .toLowerCase()
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9\u4e00-\u9fff&+./' -]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

export function artistStature(artist: string, title = ""): number {
  const n = norm(artist);
  const blob = `${n} ${norm(title)}`;
  if (!n) return 18;

  const tokens = n.split(" ").filter(Boolean);
  for (const t of tokens) {
    if (EXACT.has(t)) return 94;
  }
  if (EXACT.has(n)) return 94;

  for (const name of FUZZY_SET) {
    if (n === name) return 92;
    if (n.includes(name) || name.includes(n)) {
      if (Math.min(n.length, name.length) >= 6) return 88;
    }
  }

  if (LABEL_HINTS.some((h) => blob.includes(h))) return 70;

  const collab = artist.includes(",") || artist.includes("&") || artist.includes("/") || artist.includes(" feat");
  if (collab && n.length > 18) return 52;

  return 24;
}
