/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiCoverRouteImport } from './routes/api/cover'
import { Route as ApiRadarRouteImport } from './routes/api/radar'
import { Route as ApiRefBridgeRouteImport } from './routes/api/ref-bridge'
import { Route as ApiSyncRouteImport } from './routes/api/sync'
import { Route as ApiVaultRouteImport } from './routes/api/vault'
import { Route as ApiWebReleasesRouteImport } from './routes/api/web-releases'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCoverRoute = ApiCoverRouteImport.update({
  id: '/api/cover',
  path: '/api/cover',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRadarRoute = ApiRadarRouteImport.update({
  id: '/api/radar',
  path: '/api/radar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRefBridgeRoute = ApiRefBridgeRouteImport.update({
  id: '/api/ref-bridge',
  path: '/api/ref-bridge',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSyncRoute = ApiSyncRouteImport.update({
  id: '/api/sync',
  path: '/api/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVaultRoute = ApiVaultRouteImport.update({
  id: '/api/vault',
  path: '/api/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebReleasesRoute = ApiWebReleasesRouteImport.update({
  id: '/api/web-releases',
  path: '/api/web-releases',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/cover': typeof ApiCoverRoute
  '/api/radar': typeof ApiRadarRoute
  '/api/ref-bridge': typeof ApiRefBridgeRoute
  '/api/sync': typeof ApiSyncRoute
  '/api/vault': typeof ApiVaultRoute
  '/api/web-releases': typeof ApiWebReleasesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/cover': typeof ApiCoverRoute
  '/api/radar': typeof ApiRadarRoute
  '/api/ref-bridge': typeof ApiRefBridgeRoute
  '/api/sync': typeof ApiSyncRoute
  '/api/vault': typeof ApiVaultRoute
  '/api/web-releases': typeof ApiWebReleasesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/cover': typeof ApiCoverRoute
  '/api/radar': typeof ApiRadarRoute
  '/api/ref-bridge': typeof ApiRefBridgeRoute
  '/api/sync': typeof ApiSyncRoute
  '/api/vault': typeof ApiVaultRoute
  '/api/web-releases': typeof ApiWebReleasesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/cover'
    | '/api/radar'
    | '/api/ref-bridge'
    | '/api/sync'
    | '/api/vault'
    | '/api/web-releases'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/cover'
    | '/api/radar'
    | '/api/ref-bridge'
    | '/api/sync'
    | '/api/vault'
    | '/api/web-releases'
  id:
    | '__root__'
    | '/'
    | '/api/cover'
    | '/api/radar'
    | '/api/ref-bridge'
    | '/api/sync'
    | '/api/vault'
    | '/api/web-releases'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiCoverRoute: typeof ApiCoverRoute
  ApiRadarRoute: typeof ApiRadarRoute
  ApiRefBridgeRoute: typeof ApiRefBridgeRoute
  ApiSyncRoute: typeof ApiSyncRoute
  ApiVaultRoute: typeof ApiVaultRoute
  ApiWebReleasesRoute: typeof ApiWebReleasesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cover': {
      id: '/api/cover'
      path: '/api/cover'
      fullPath: '/api/cover'
      preLoaderRoute: typeof ApiCoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/radar': {
      id: '/api/radar'
      path: '/api/radar'
      fullPath: '/api/radar'
      preLoaderRoute: typeof ApiRadarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ref-bridge': {
      id: '/api/ref-bridge'
      path: '/api/ref-bridge'
      fullPath: '/api/ref-bridge'
      preLoaderRoute: typeof ApiRefBridgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sync': {
      id: '/api/sync'
      path: '/api/sync'
      fullPath: '/api/sync'
      preLoaderRoute: typeof ApiSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vault': {
      id: '/api/vault'
      path: '/api/vault'
      fullPath: '/api/vault'
      preLoaderRoute: typeof ApiVaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/web-releases': {
      id: '/api/web-releases'
      path: '/api/web-releases'
      fullPath: '/api/web-releases'
      preLoaderRoute: typeof ApiWebReleasesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiCoverRoute: ApiCoverRoute,
  ApiRadarRoute: ApiRadarRoute,
  ApiRefBridgeRoute: ApiRefBridgeRoute,
  ApiSyncRoute: ApiSyncRoute,
  ApiVaultRoute: ApiVaultRoute,
  ApiWebReleasesRoute: ApiWebReleasesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
